/** Legacy path aliases shared by web links, web worker, and translation worker. */
/**
 * Generated/extended from last-year public slug renames (blog frontmatter + file renames).
 * Keep old public paths working so earned backlinks are not lost.
 */
const LEGACY_PATH_REDIRECTS: Record<string, string> = {
  '/blog/ai': '/articles/',
  '/blog/ai/': '/articles/',
  '/blog/setup-ci-and-cd-gitlab': '/blog/setup-ci-and-cd-in-gitlab/',
  '/blog/open-source-licecing': '/blog/open-source-licence/',
  '/blog/release-of-a-brand-new-capacitor-social-login': '/blog/capacitor-social-login-release/',
  '/blog/Release-of-a-brand-new-capacitor-social-login': '/blog/capacitor-social-login-release/',
  '/blog/birth-of-capgo-my-challenging-journey-as-a-solo-maker': '/blog/birth-of-capgo-revolutionizing-capacitor-app-updates/',
  '/blog/how-rapido-cloud-manage-semantic-rerlease-with-CapGo-CapacitorUpdater': '/blog/how-I-manage-semantic-release-with-CapGo-CapacitorUpdater/',
  '/blog/introducing-end-A-end-Seguridad-A-Capacitor-updater-with-code-signing': '/blog/introducing-end-to-end-security-to-capacitor-updater-with-code-signing/',
  '/blog/building-a-native-mobile-app-with-nuxt-3-and-capacitor': '/blog/building-a-native-mobile-app-with-nuxt-and-capacitor/',
  '/blog/alternative-to-capawesome': '/capwesome/',
  '/blog/capgo-vs-capawesome-comparing-ota-update-plugins': '/capwesome/',
  '/blog/how-to-use-capacitor-with-nextjs': '/blog/nextjs-mobile-app-capacitor-from-scratch/',
  '/blog/gestione-dei-changelog-di-capacitor-guida-completa': '/blog/capacitor-comprehensive-guide/#is-there-enterprise-specific-support-available',
  '/blog/about-open-source': '/blog/open-source/',
  '/blog/activar-modo-desarrollador-ios16': '/blog/enable-ios-developer-mode-ios16/',
  '/blog/actualizaciones-en-tiempo-real-con-segmentación-de-usuarios': '/blog/real-time-updates-with-user-segmentation/',
  '/blog/actualizaciones-en-vivo-en-apple': '/blog/do-apple-allow-live-updates/',
  '/blog/actualizaciones-en-vivo-para-aplicacion-flutter': '/blog/live-updates-for-flutter-app/',
  '/blog/actualizaciones-en-vivo-permitidas-por-google': '/blog/do-google-allow-live-updates/',
  '/blog/actualizaciones-ota-de-capacitor-vs-metodos-de-prueba-tradicionales': '/blog/capacitor-ota-updates-vs-traditional-testing-methods/',
  '/blog/actualizaciones-ota-en-cicd-consejos-de-seguridad-y-cumplimiento': '/blog/ota-updates-in-cicd-security-and-compliance-tips/',
  '/blog/actualizar-sus-aplicaciones-capacitor-sin-problemas-con-capacitor-updater': '/blog/update-your-capacitor-apps-seamlessly-using-capacitor-updater/',
  '/blog/aggiornamenti-capacitor-ota-vs-metodi-di-test-tradizionali': '/blog/capacitor-ota-updates-vs-traditional-testing-methods/',
  '/blog/aggiornamenti-in-diretta-autohospitati': '/blog/self-hosted-live-updates/',
  '/blog/aggiornamenti-ota-capacitor-migliorare-prestazioni-dispositivi-basso-livello': '/blog/capacitor-ota-updates-boosting-low-end-device-performance/',
  '/blog/aggiornamenti-ota-in-beta-rispettare-policy': '/blog/ota-updates-in-beta-staying-policy-compliant/',
  '/blog/aggiornamenti-ota-su-ios-vs-android-tramite-capacitor': '/blog/capacitor-ota-updates-targeting-ios-vs-android/',
  '/blog/aggiornamenti-policy-apple-per-app-capacitor-2025': '/blog/apple-policy-updates-for-capacitor-apps-2025/',
  '/blog/aggiornamento-automatico-con-quasar-e-capacitor': '/blog/quasar-mobile-app-capacitor/',
  '/blog/aggiornamento-da-capacitor-4-a-capacitor-5': '/blog/updating-from-capacitor-4-to-capacitor-5/',
  '/blog/alternativa-a-capawesome': '/capwesome/',
  '/blog/alternativa-a-expo': '/blog/alternative-to-expo/',
  '/blog/alternativa-a-voltbuilder': '/blog/alternative-to-voltbuilder/',
  '/blog/alternativa-ad-appflow': '/blog/alternative-to-appflow/',
  '/blog/alternativa-chiusura-appflow': '/blog/appflow-shutdown-alternative/',
  '/blog/alternative-a-voltbuilder': '/blog/alternative-to-voltbuilder/',
  '/blog/android-desactivar-talkback': '/blog/turn-off-android-talkback/',
  '/blog/android-desactiver-talkback': '/blog/turn-off-android-talkback/',
  '/blog/android-talkback-deaktivieren': '/blog/turn-off-android-talkback/',
  '/blog/api-rate-limiting-für-app-store-konformität': '/blog/api-rate-limiting-for-app-store-compliance/',
  '/blog/apple-policy-updates-für-capacitor-apps-2025': '/blog/apple-policy-updates-for-capacitor-apps-2025/',
  '/blog/apple-vs-google-privacy-compliance-per-dati-di-terze-parti': '/blog/apple-vs-google-privacy-compliance-for-third-party-data/',
  '/blog/application-mobile-vue-capacitor': '/blog/vue-mobile-app-capacitor/',
  '/blog/applications-capacitor-et-lois-sur-les-donnees-russes-conseils-de-conformite': '/blog/capacitor-apps-and-russias-data-laws-compliance-tips/',
  '/blog/auto-hospedado-capgo': '/blog/self-hosted-capgo/',
  '/blog/best-practice-di-performance-per-aggiornamenti-ota-su-capacitor': '/blog/capacitor-ota-updates-best-practices-for-performance/',
  '/blog/best-practice-versioning-per-aggiornamenti-ota-in-capacitor': '/blog/capacitor-ota-updates-versioning-best-practices/',
  '/blog/Bewährte Methoden zur Versionierung von Capacitor OTA-Updates': '/blog/capacitor-ota-updates-versioning-best-practices/',
  '/blog/bonnes-pratiques-pour-l-approbation-des-mises-a-jour-ota': '/blog/user-consent-for-ota-updates-best-practices/',
  '/blog/build-e-release-automatico-con-github-actions': '/blog/automatic-build-and-release-with-github-actions/',
  '/blog/building-a-native-mobile-app-with-nuxt-4-and-capacitor': '/blog/building-a-native-mobile-app-with-nuxt-and-capacitor/',
  '/blog/Capacitor OTA-Updates vs. traditionelle Versionierung': '/blog/capacitor-ota-updates-vs-traditional-versioning/',
  '/blog/capacitor-live-updates-rimanere-conformi-alle-regole-di-apple': '/blog/capacitor-live-updates-staying-compliant-with-apple/',
  '/blog/capacitor-ota-updates-cible-ios-vs-android': '/blog/capacitor-ota-updates-targeting-ios-vs-android/',
  '/blog/capacitor-ota-updates-vs-traditionelle-testmethoden': '/blog/capacitor-ota-updates-vs-traditional-testing-methods/',
  '/blog/capacitor-vs-appflow-ota-update-loesungen-im-vergleich': '/blog/capacitor-vs-appflow-ota-update-solutions-compared/',
  '/blog/capgo-fonctionne-t-il-avec-cordova': '/blog/do-capgo-work-for-cordova/',
  '/blog/capgo-per-aggiornamenti-ota-sicuri-app-store': '/blog/capgo-for-app-store-safe-ota-updates/',
  '/blog/ccpa-compliance-für-mobile-apps': '/blog/ccpa-compliance-for-mobile-apps/',
  '/blog/ccpa-conformite-pour-applications-mobiles': '/blog/ccpa-compliance-for-mobile-apps/',
  '/blog/checkliste-zur-validierung-von-capacitor-app-aktualisierungen': '/blog/checklist-for-validating-capacitor-app-updates/',
  '/blog/colli-di-bottiglia-comuni-cicd-nelle-pipeline-ota': '/blog/common-cicd-bottlenecks-in-ota-pipelines/',
  '/blog/comandos-cli-comunes-de-capacitor-problemas-y-soluciones': '/blog/capacitor-cli-commands-common-issues-and-fixes/',
  '/blog/come-aggirare-controllo-app-store': '/blog/how-to-bypass-app-store-review/',
  '/blog/come-aggiungere-dipendenze-nei-plugin-capacitor': '/blog/how-to-add-dependencies-in-capacitor-plugins/',
  '/blog/come-aggiungere-il-targeting-geolocalizzato-agli-aggiornamenti-ota': '/blog/how-to-add-geolocation-targeting-to-ota-updates/',
  '/blog/come-costruire-un-app-capacitor-in-xcode-cloud': '/blog/how-to-build-capacitor-app-in-xcode-cloud/',
  '/blog/come-funziona-la-versione-in-capgo': '/blog/how-version-work-in-capgo/',
  '/blog/come-gestire-le-richieste-dei-dati-degli-utenti-secondo-il-ccpa': '/blog/how-to-handle-user-data-requests-under-ccpa/',
  '/blog/come-gli-aggiornamenti-delta-riducono-le-dimensioni-del-payload': '/blog/how-delta-updates-reduce-payload-size/',
  '/blog/come-gli-aggiornamenti-ota-influenzano-la-sicurezza-dell-app-store': '/blog/how-ota-updates-affect-app-store-security/',
  '/blog/come-inviare-una-versione-specifica-agli-utenti': '/blog/how-to-send-specific-version-to-users/',
  '/blog/come-la-crittografia-end-to-end-protegge-gli-aggiornamenti': '/blog/how-end-to-end-encryption-secures-updates/',
  '/blog/come-le-leggi-sui-dati-cinesi-influenzano-linvio-delle-app-negli-store': '/blog/how-chinas-data-laws-impact-app-store-submissions/',
  '/blog/come-monitorare-gli-aggiornamenti-delle-app-capacitor': '/blog/how-to-monitor-capacitor-app-updates/',
  '/blog/come-personalizzare-gli-script-di-build-con-capacitor-cli': '/blog/how-to-customize-build-scripts-with-capacitor-cli/',
  '/blog/come-pianificare-aggiornamenti-ota-per-app-capacitor': '/blog/how-to-schedule-ota-updates-for-capacitor-apps/',
  '/blog/come-profilare-app-multi-piattaforma-con-capacitor': '/blog/how-to-profile-cross-platform-apps-with-capacitor/',
  '/blog/come-rapido-cloud-gestisce-semantic-release-con-CapGo-CapacitorUpdater': '/blog/how-I-manage-semantic-release-with-CapGo-CapacitorUpdater/',
  '/blog/come-rbac-protegge-gli-aggiornamenti-ota-nelle-app-capacitor': '/blog/how-rbac-secures-ota-updates-in-capacitor-apps/',
  '/blog/come-risolvere-errori-di-compilazione-android-in-capacitor': '/blog/how-to-resolve-android-build-errors-in-capacitor/',
  '/blog/come-usare-file-aar-nei-plugin-capacitor': '/blog/how-to-use-aar-files-in-capacitor-plugins/',
  '/blog/come-utilizzare-il-semantic-versioning-con-gli-aggiornamenti-capgo-ota': '/blog/how-to-use-semantic-versioning-with-capgo-ota-updates/',
  '/blog/come-utilizzare-la-documentazione-di-capgo-per-gli-aggiornamenti-ota': '/blog/how-to-use-capgo-documentation-for-ota-updates/',
  '/blog/Comment faire une version majeure dans Capgo': '/blog/how-to-release-major-version-in-capgo/',
  '/blog/comment-ajouter-la-geolocalisation-pour-les-mises-a-jour-ota': '/blog/how-to-add-geolocation-targeting-to-ota-updates/',
  '/blog/comment-capacitor-connecte-le-code-web-et-natif': '/blog/how-capacitor-bridges-web-and-native-code/',
  '/blog/comment-declencher-des-mises-a-jour-ota-avec-les-outils-cicd': '/blog/how-cicd-tools-trigger-ota-updates/',
  '/blog/comment-est-né-capgo': '/blog/how-capgo-is-born/',
  '/blog/comment-eviter-la-verification-de-l-app-store': '/blog/how-to-bypass-app-store-review/',
  '/blog/comment-fonctionnent-les-deploiements-progressifs-google-play': '/blog/google-play-staged-rollouts-how-it-works/',
  '/blog/comment-gerer-les-donnees-utilisateur-dans-les-applications-capacitor': '/blog/how-to-handle-user-data-in-capacitor-apps/',
  '/blog/comment-la-conformite-ccpa-impacte-les-applications': '/blog/how-ccpa-enforcement-impacts-apps/',
  '/blog/comment-le-chiffrement-de-bout-en-bout-protège-les-mises-à-jour': '/blog/how-end-to-end-encryption-secures-updates/',
  '/blog/comment-le-chiffrement-ota-est-conforme-aux-normes-app-store': '/blog/how-ota-encryption-meets-app-store-compliance/',
  '/blog/comment-les-mises-a-jour-ota-affectent-la-securite-de-l-app-store': '/blog/how-ota-updates-affect-app-store-security/',
  '/blog/comment-les-mises-à-jour-delta-réduisent-la-taille-de-la-charge-utile': '/blog/how-delta-updates-reduce-payload-size/',
  '/blog/comment-résoudre-les-erreurs-de-compilation-android-dans-capacitor': '/blog/how-to-resolve-android-build-errors-in-capacitor/',
  "/blog/comment-surveiller-les-mises-à-jour-de-l'application-capacitor": '/blog/how-to-monitor-capacitor-app-updates/',
  '/blog/comment-utiliser-capacitor-cli-pour-les-mises-à-jour-ota': '/blog/how-to-use-capacitor-cli-for-ota-updates/',
  '/blog/comment-utiliser-les-fichiers-aar-dans-les-plugins-capacitor': '/blog/how-to-use-aar-files-in-capacitor-plugins/',
  '/blog/como-administrar-datos-de-usuario-en-aplicaciones-capacitor': '/blog/how-to-handle-user-data-in-capacitor-apps/',
  '/blog/como-agregar-dependencias-en-plugins-de-capacitor': '/blog/how-to-add-dependencies-in-capacitor-plugins/',
  '/blog/como-enviar-una-version-especifica-a-usuarios': '/blog/how-to-send-specific-version-to-users/',
  '/blog/como-evitar-la-revision-de-la-app-store': '/blog/how-to-bypass-app-store-review/',
  '/blog/como-funciona-el-puente-nativo-en-aplicaciones-capacitor-android': '/blog/how-native-bridge-works-in-capacitor-android-apps/',
  '/blog/como-las-aplicaciones-moviles-cumplen-con-las-leyes-de-privacidad-de-eeuu': '/blog/how-mobile-apps-stay-compliant-with-us-privacy-laws/',
  '/blog/como-los-ota-updates-afectan-la-seguridad-de-la-app-store': '/blog/how-ota-updates-affect-app-store-security/',
  '/blog/como-nacio-capgo': '/blog/how-capgo-is-born/',
  '/blog/como-procesar-solicitudes-de-usuarios-segun-ccpa': '/blog/how-to-handle-user-data-requests-under-ccpa/',
  '/blog/como-rapido-cloud-maneja-semantic-rerlease-con-CapGo-CapacitorUpdater': '/blog/how-I-manage-semantic-release-with-CapGo-CapacitorUpdater/',
  '/blog/como-resolver-errores-de-compilacion-de-android-en-capacitor': '/blog/how-to-resolve-android-build-errors-in-capacitor/',
  '/blog/como-se-aseguran-las-actualizaciones-ota-con-la-gestion-de-claves': '/blog/how-to-secure-ota-updates-with-key-management/',
  '/blog/Comparaison entre les déploiements progressifs et les versions complètes': '/blog/staged-rollouts-vs-full-releases-comparison/',
  '/blog/comparaison-react-native-vs-capacitor': '/blog/comparing-react-native-vs-capacitor/',
  '/blog/compilation-android-capacitor-automatique-avec-github-action': '/blog/automatic-capacitor-android-build-github-action/',
  '/blog/compliance-pruefungen-in-cicd-fuer-capacitor-apps': '/blog/compliance-checks-in-cicd-for-capacitor-apps/',
  '/blog/compras-in-app-capacitor': '/blog/in-app-purchases-capacitor/',
  '/blog/comprendiendo-el-manifiesto-de-privacidad-de-apple': '/blog/understanding-apples-privacy-manifest/',
  '/blog/condivisione-dati-e-politiche-delle-app-capacitor': '/blog/capacitor-apps-and-data-sharing-policies/',
  '/blog/configuracion-ci-y-cd-gitlab': '/blog/setup-ci-and-cd-in-gitlab/',
  '/blog/configuracion-de-monitoreo-de-rendimiento-das-en-capacitor': '/blog/set-up-performance-monitoring-in-capacitor/',
  '/blog/configuracion-del-entorno-local-de-capacitor': '/blog/setting-up-capacitor-local-environment/',
  '/blog/configuración-del-proyecto-cli-de-capacitor': '/blog/capacitor-cli-project-setup-guide/',
  '/blog/configuration-ci-et-cd-gitlab': '/blog/setup-ci-and-cd-in-gitlab/',
  '/blog/configurazione-ambiente-locale-capacitor': '/blog/setting-up-capacitor-local-environment/',
  '/blog/configurazione-ci-e-cd-gitlab': '/blog/setup-ci-and-cd-in-gitlab/',
  '/blog/configurazione-cicd-per-app-capacitor': '/blog/setting-up-cicd-for-capacitor-apps/',
  '/blog/conformità-ccpa-per-app-mobili': '/blog/ccpa-compliance-for-mobile-apps/',
  '/blog/consenso-utente-per-aggiornamenti-ota-best-practices': '/blog/user-consent-for-ota-updates-best-practices/',
  '/blog/construire-une-application-mobile-native-avec-nuxt-3-et-capacitor': '/blog/building-a-native-mobile-app-with-nuxt-and-capacitor/',
  '/blog/corrige-conflictos-de-version-capacitor': '/blog/fix-capacitor-version-mismatch-errors/',
  '/blog/costruire-una-app-mobile-nativa-con-nextjs-e-capacitor': '/blog/building-a-native-mobile-app-with-nextjs-and-capacitor/',
  '/blog/crea-app-mobile-react-con-capacitor': '/blog/create-react-mobile-apps-with-capacitor/',
  '/blog/creando-aplicaciones-moviles-con-sveltekit-y-capacitor': '/blog/creating-mobile-apps-with-sveltekit-and-capacitor/',
  '/blog/crear-aplicaciones-móviles-react-con-capacitor': '/blog/create-react-mobile-apps-with-capacitor/',
  '/blog/crear-pantalla-offline-en-vue-angular-react': '/blog/create-offline-screen-in-vue-angular-react/',
  '/blog/creation-et-suppression-de-canaux-de-mise-a-jour-dans-capacitor': '/blog/creating-and-deleting-update-channels-in-capacitor/',
  '/blog/creazione-automatica-capacitor-ios-codemagic': '/blog/automatic-capacitor-ios-build-codemagic/',
  '/blog/creazione-di-app-mobile-con-sveltekit-e-capacitor': '/blog/creating-mobile-apps-with-sveltekit-and-capacitor/',
  '/blog/creazione-ed-eliminazione-dei-canali-di-aggiornamento-in-capacitor': '/blog/creating-and-deleting-update-channels-in-capacitor/',
  '/blog/criteri-di-unione-per-team-utilizzando-app-capacitor': '/blog/merge-policies-for-teams-using-capacitor-apps/',
  '/blog/création-automatique-ios-capacitor-avec-codemagic': '/blog/automatic-capacitor-ios-build-codemagic/',
  '/blog/création-dune-application-mobile-native-avec-nextjs-et-capacitor': '/blog/building-a-native-mobile-app-with-nextjs-and-capacitor/',
  '/blog/Cómo agregar plugins de terceros en aplicaciones Capacitor': '/blog/how-to-add-third-party-plugins-in-capacitor-apps/',
  '/blog/cómo-el-cifrado-ota-cumple-con-las-normas-de-la-app-store': '/blog/how-ota-encryption-meets-app-store-compliance/',
  '/blog/cómo-funciona-la-versión-en-capgo': '/blog/how-version-work-in-capgo/',
  '/blog/cómo-se-cuenta-tu-uso': '/blog/how-your-usage-is-counted/',
  '/blog/das-datenschutzmanifest-von-apple-verstehen': '/blog/understanding-apples-privacy-manifest/',
  '/blog/das-performance-monitoring-in-capacitor-einrichten': '/blog/set-up-performance-monitoring-in-capacitor/',
  '/blog/das-ultimative-handbuch-für-capacitor-ota-updates': '/blog/ultimate-guide-to-capacitor-ota-updates/',
  '/blog/datenschutz-manifest-für-capacitor-apps-leitfaden': '/blog/privacy-manifest-for-capacitor-apps-guide/',
  '/blog/datenschutzgesetze-der-bundesstaaten-fuer-mobile-apps-vergleich': '/blog/state-privacy-laws-for-mobile-apps-comparison/',
  '/blog/Der ultimative Leitfaden zur OTA-Update-Sicherheit für Capacitor-Apps': '/blog/ultimate-guide-to-ota-update-security-for-capacitor-apps/',
  '/blog/despliegue-controlado-para-capacitor-live-updates': '/blog/phased-rollouts-for-capacitor-live-updates/',
  '/blog/Diferencias de versión entre Capacitor y Appflow': '/blog/capacitor-vs-appflow-versioning-differences/',
  '/blog/differenze-chiave-tra-sviluppo-e-produzione-nelle-app-capacitor': '/blog/development-vs-production-key-differences-in-capacitor-apps/',
  '/blog/Différences de version entre Capacitor et Appflow': '/blog/capacitor-vs-appflow-versioning-differences/',
  '/blog/différences-clés-entre-les-plugins-capacitor-cicd-et-appflow': '/blog/capacitor-cicd-plugins-vs-appflow-key-differences/',
  '/blog/différences-entre-développement-et-production-dans-les-applications-capacitor': '/blog/development-vs-production-key-differences-in-capacitor-apps/',
  '/blog/Directives de fusion pour les équipes utilisant des applications Capacitor': '/blog/merge-policies-for-teams-using-capacitor-apps/',
  '/blog/Directrices de fusión para equipos que utilizan aplicaciones Capacitor': '/blog/merge-policies-for-teams-using-capacitor-apps/',
  '/blog/disattiva-android-talkback': '/blog/turn-off-android-talkback/',
  '/blog/dépannage-des-mises-à-jour-capacitor-ota': '/blog/capacitor-ota-updates-debugging-issues/',
  '/blog/développement-applications-multiplateformes-avec-capacitorjs': '/blog/developing-cross-platform-apps-with-capacitorjs/',
  '/blog/einrichten-der-lokalen-capacitor-umgebung': '/blog/setting-up-capacitor-local-environment/',
  '/blog/einrichten-von-cicd-für-capacitor-apps': '/blog/setting-up-cicd-for-capacitor-apps/',
  '/blog/entwicklung-vs-produktiv-unterschiede-in-capacitor-apps': '/blog/development-vs-production-key-differences-in-capacitor-apps/',
  '/blog/Erklärung zum Capacitor OTA Update Versions-Targeting': '/blog/capacitor-ota-updates-version-targeting-explained/',
  '/blog/errores-comunes-en-la-segmentacion-de-atributos-personalizados': '/blog/common-mistakes-in-custom-attribute-segmentation/',
  '/blog/estrategias-de-rollback-para-actualizaciones-en-vivo-de-capacitor': '/blog/rollback-strategies-for-capacitor-live-updates/',
  '/blog/etiquetado-de-versiones-en-aplicaciones-capacitor': '/blog/version-tagging-in-capacitor-apps/',
  '/blog/Explication des scripts npm pour les mises à jour OTA Capacitor': '/blog/npm-scripts-for-capacitor-ota-updates-explained/',
  '/blog/fehlerprotokollierung-tools-fuer-capacitor-ota-updates': '/blog/error-logging-tools-for-capacitor-ota-updates/',
  '/blog/fondements-plugin-android-natif-bridge-capacitor': '/blog/capacitor-native-bridge-android-plugin-basics/',
  '/blog/foros-de-la-comunidad-capacitor-para-desarrolladores-de-plugins': '/blog/capacitor-community-forums-for-plugin-developers/',
  '/blog/funciona-capgo-con-cordova': '/blog/do-capgo-work-for-cordova/',
  '/blog/funktioniert-capgo-mit-cordova': '/blog/do-capgo-work-for-cordova/',
  '/blog/gestion-de-dependencias-en-proyectos-capacitor': '/blog/managing-dependencies-in-capacitor-projects/',
  '/blog/gestion-des-clés-sous-la-réglementation-chinoise-sur-le-chiffrement': '/blog/key-management-under-chinas-encryption-rules/',
  '/blog/gestion-des-dependances-dans-les-projets-capacitor': '/blog/managing-dependencies-in-capacitor-projects/',
  '/blog/gestion-des-erreurs-dans-les-applications-capacitor-meilleures-pratiques-ux': '/blog/error-handling-in-capacitor-apps-ux-best-practices/',
  '/blog/gestionar-compilacion-dev-y-prod-con-github-actions': '/blog/manage-dev-and-prod-build-with-github-actions/',
  '/blog/gestione-degli-errori-nelle-app-capacitor-best-practice-ux': '/blog/error-handling-in-capacitor-apps-ux-best-practices/',
  '/blog/gestione-dei-conflitti-di-versione-in-capacitor-live-updates': '/blog/capacitor-live-updates-handling-version-conflicts/',
  '/blog/gestione-dei-segreti-nelle-pipeline-cicd': '/blog/managing-secrets-in-cicd-pipelines/',
  '/blog/gestire-build-dev-e-prod-con-github-actions': '/blog/manage-dev-and-prod-build-with-github-actions/',
  '/blog/git-flow-contro-trunk-based-per-cicd': '/blog/git-flow-vs-trunk-based-for-cicd/',
  '/blog/git-flow-vs-trunk-based-für-cicd': '/blog/git-flow-vs-trunk-based-for-cicd/',
  '/blog/git-flow-vs-trunk-based-para-cicd': '/blog/git-flow-vs-trunk-based-for-cicd/',
  '/blog/google-play-distribuzione-scaglionata-come-funziona': '/blog/google-play-staged-rollouts-how-it-works/',
  '/blog/google-und-apple-datenschutz-compliance-fuer-drittanbieterdaten': '/blog/apple-vs-google-privacy-compliance-for-third-party-data/',
  '/blog/guia-paso-a-paso-para-registrar-icp-para-aplicaciones-moviles-en-china': '/blog/icp-filing-for-mobile-apps-in-china-step-by-step-guide/',
  '/blog/guida-alla-configurazione-del-pipeline-ci-cd-di-capacitor': '/blog/capacitor-cicd-pipeline-setup-guide/',
  '/blog/guida-approvazione-app-store-aggiornamenti-ota-capacitor': '/blog/capacitor-ota-updates-app-store-approval-guide/',
  '/blog/guida-completa-al-debugging-delle-app-capacitor': '/blog/ultimate-guide-to-debugging-capacitor-apps/',
  '/blog/guida-configurazione-progetto-capacitor-cli': '/blog/capacitor-cli-project-setup-guide/',
  '/blog/guida-definitiva-agli-aggiornamenti-ota-conformi-all-app-store': '/blog/ultimate-guide-to-app-store-compliant-ota-updates/',
  '/blog/guida-step-by-step-per-la-registrazione-icp-delle-app-mobili-in-cina': '/blog/icp-filing-for-mobile-apps-in-china-step-by-step-guide/',
  "/blog/Guide d'intégration de Capgo avec GitHub Actions": '/blog/capgo-integration-with-github-actions-guide/',
  '/blog/guide-approbation-app-store-capacitor-ota-updates': '/blog/capacitor-ota-updates-app-store-approval-guide/',
  '/blog/guide-complet-de-capacitor': '/blog/capacitor-comprehensive-guide/',
  '/blog/guide-configuration-pipeline-cicd-capacitor': '/blog/capacitor-cicd-pipeline-setup-guide/',
  "/blog/guide-d'intégration-cicd-mises-à-jour-ota-capacitor": '/blog/capacitor-ota-updates-cicd-integration-guide/',
  '/blog/guide-de-contribution-plugin-capacitor': '/blog/capacitor-plugin-contribution-guide/',
  '/blog/guide-de-debogage-des-applications-capacitor': '/blog/ultimate-guide-to-debugging-capacitor-apps/',
  "/blog/guide-du-développement-d'applications-mobiles-multiplateformes-2024": '/blog/cross-platform-mobile-app-development-guide-2024/',
  '/blog/guide-sur-la-politique-de-confidentialité-pour-les-apps-capacitor': '/blog/privacy-manifest-for-capacitor-apps-guide/',
  "/blog/guide-étape-par-étape-pour-l'initialisation-d'une-application-capacitor": '/blog/capacitor-app-initialization-step-by-step-guide/',
  '/blog/guía-completa-de-capacitor': '/blog/capacitor-comprehensive-guide/',
  '/blog/guía-definitiva-manejo-changelog-capacitor': '/blog/capacitor-changelog-management-ultimate-guide/',
  '/blog/guía-para-depurar-aplicaciones-capacitor': '/blog/ultimate-guide-to-debugging-capacitor-apps/',
  '/blog/génération-ios-automatique-capacitor-avec-github-action-et-match': '/blog/automatic-capacitor-ios-build-github-action-with-match/',
  '/blog/herramientas-principales-para-depurar-actualizaciones-ota-en-capacitor': '/blog/top-tools-for-debugging-ota-updates-in-capacitor/',
  '/blog/how-rapido-cloud-manage-semantic-rerlease-with-Capgo-CapacitorUpdater': '/blog/how-I-manage-semantic-release-with-CapGo-CapacitorUpdater/',
  '/blog/how-to-migrate-a-capacitor-plugin-to-spm': '/blog/how-to-migrate-your-capacitor-app-to-spm/',
  '/blog/häufige-engpässe-bei-der-cicd-pipeline-für-ota-aktualisierungen': '/blog/common-cicd-bottlenecks-in-ota-pipelines/',
  '/blog/häufige-live-update-probleme-und-lösungen-für-entwickler': '/blog/common-live-update-issues-and-solutions-for-developers/',
  '/blog/il-capgo-funziona-per-cordova': '/blog/do-capgo-work-for-cordova/',
  '/blog/impostazione-del-monitoraggio-delle-prestazioni-in-capacitor': '/blog/set-up-performance-monitoring-in-capacitor/',
  '/blog/integrar-universal-links-capacitor-nextjs': '/blog/integrate-universal-links-capacitor-nextjs/',
  '/blog/integrazione-di-capgo-con-guida-alle-github-actions': '/blog/capgo-integration-with-github-actions-guide/',
  '/blog/integridad-del-codigo-en-aplicaciones-capacitor-tecnicas-clave': '/blog/code-integrity-in-capacitor-apps-key-techniques/',
  '/blog/integrite-du-code-dans-les-applications-capacitor-techniques-cles': '/blog/code-integrity-in-capacitor-apps-key-techniques/',
  '/blog/integrità-del-codice-nelle-app-capacitor-tecniche-chiave': '/blog/code-integrity-in-capacitor-apps-key-techniques/',
  '/blog/Integritätsprüfungen für Capacitor-Updates': '/blog/integrity-checks-for-capacitor-updates/',
  '/blog/konfiguration-des-rollbacks-fuer-capacitor-updates': '/blog/configuring-rollback-for-capacitor-updates/',
  '/blog/kontrollierte-bereitstellung-für-capacitor-live-updates': '/blog/phased-rollouts-for-capacitor-live-updates/',
  '/blog/korrigiere-capacitor-versionskonflikte': '/blog/fix-capacitor-version-mismatch-errors/',
  '/blog/la-conformita-pipeda-per-app-mobili-in-canada': '/blog/pipeda-compliance-for-mobile-apps-in-canada/',
  '/blog/leitfaden-zum-debuggen-von-capacitor-apps': '/blog/ultimate-guide-to-debugging-capacitor-apps/',
  '/blog/les-applications-capacitor-et-les-politiques-de-partage-de-données': '/blog/capacitor-apps-and-data-sharing-policies/',
  '/blog/leyes-estatales-de-privacidad-para-apps-moviles-comparativa': '/blog/state-privacy-laws-for-mobile-apps-comparison/',
  '/blog/Licences open source': '/blog/open-source-licence/',
  '/blog/limitation-du-taux-api-pour-la-conformité-app-store': '/blog/api-rate-limiting-for-app-store-compliance/',
  '/blog/limitazione-della-frequenza-delle-api-per-conformità-app-store': '/blog/api-rate-limiting-for-app-store-compliance/',
  '/blog/lista-de-verificacion-leyes-privacidad-eeuu-apps-moviles': '/blog/us-privacy-laws-mobile-app-checklist/',
  '/blog/lista-de-verificacion-para-validar-actualizaciones-de-aplicaciones-capacitor': '/blog/checklist-for-validating-capacitor-app-updates/',
  '/blog/lista-de-verificación-de-seguridad-para-actualizaciones-ota-en-apps-capacitor': '/blog/ota-security-checklist-for-capacitor-apps/',
  '/blog/lista-de-verificación-para-la-firma-de-tokens-en-aplicaciones-capacitor': '/blog/checklist-for-token-signing-in-capacitor-apps/',
  '/blog/lista-di-controllo-della-sicurezza-ota-per-app-capacitor': '/blog/ota-security-checklist-for-capacitor-apps/',
  '/blog/liste-de-controle-lois-confidentialite-usa-applications-mobiles': '/blog/us-privacy-laws-mobile-app-checklist/',
  '/blog/liste-de-verification-pour-valider-les-mises-a-jour-des-applications-capacitor': '/blog/checklist-for-validating-capacitor-app-updates/',
  '/blog/live-update-with-quasar-and-capacitor': '/blog/quasar-mobile-app-capacitor/',
  '/blog/live-update-with-quasar-und-capacitor': '/blog/quasar-mobile-app-capacitor/',
  '/blog/live-updates-faq-antworten-für-app-entwickler': '/blog/live-updates-faq-answers-for-app-developers/',
  '/blog/live-updates-für-flutter-app': '/blog/live-updates-for-flutter-app/',
  '/blog/Lo que necesita saber sobre los plugins de Capacitor': '/blog/capacitor-plugins-what-you-need-to-know/',
  '/blog/lois-etatiques-sur-la-confidentialite-des-applications-mobiles-comparaison': '/blog/state-privacy-laws-for-mobile-apps-comparison/',
  '/blog/manifiesto-de-privacidad-para-apps-de-capacitor-guia': '/blog/privacy-manifest-for-capacitor-apps-guide/',
  '/blog/Mejores prácticas para el versionado de actualizaciones OTA de Capacitor': '/blog/capacitor-ota-updates-versioning-best-practices/',
  '/blog/mejores-practicas-de-rendimiento-para-actualizaciones-ota-en-capacitor': '/blog/capacitor-ota-updates-best-practices-for-performance/',
  '/blog/mejores-prácticas-actualizaciones-ota-staging': '/blog/staging-ota-updates-best-practices/',
  '/blog/mejores-prácticas-para-aprobación-de-actualizaciones-ota': '/blog/user-consent-for-ota-updates-best-practices/',
  '/blog/memorizzazione-sicura-per-token-offline-in-capacitor': '/blog/secure-storage-for-offline-tokens-in-capacitor/',
  '/blog/Merge-Richtlinien für Teams, die Capacitor-Apps verwenden': '/blog/merge-policies-for-teams-using-capacitor-apps/',
  '/blog/migrating-cordova-zu-capacitor': '/blog/migrating-cordova-to-capacitor/',
  '/blog/migrazione-appcenter': '/blog/appcenter-migration/',
  '/blog/mise-a-jour-de-capacitor-4-vers-capacitor-5': '/blog/updating-from-capacitor-4-to-capacitor-5/',
  '/blog/mise-a-jour-de-vos-applications-capacitor-sans-probleme-avec-capacitor-updater': '/blog/update-your-capacitor-apps-seamlessly-using-capacitor-updater/',
  '/blog/mise-à-jour-en-direct-avec-quasar-et-capacitor': '/blog/quasar-mobile-app-capacitor/',
  '/blog/Mises à jour OTA de Capacitor vs Versionnement traditionnel': '/blog/capacitor-ota-updates-vs-traditional-versioning/',
  '/blog/mises-a-jour-ota-dans-capacitor-en-restant-conforme': '/blog/capacitor-ota-updates-staying-compliant/',
  '/blog/mises-à-jour-en-direct-autorisées-par-google': '/blog/do-google-allow-live-updates/',
  '/blog/mises-à-jour-en-direct-pour-application-flutter': '/blog/live-updates-for-flutter-app/',
  '/blog/mises-à-jour-en-direct-sur-apple': '/blog/do-apple-allow-live-updates/',
  '/blog/mises-à-jour-en-temps-réel-des-métriques-pour-les-applications-capacitor': '/blog/real-time-update-metrics-for-capacitor-apps/',
  '/blog/mises-à-jour-ota-de-capacitor-vs-restrictions-app-store': '/blog/capacitor-ota-updates-vs-app-store-restrictions/',
  '/blog/mises-à-jour-ota-en-version-beta-rester-conforme-aux-directives': '/blog/ota-updates-in-beta-staying-policy-compliant/',
  '/blog/mobile-app-update-strategien-eine-checkliste-fuer-entwickler': '/blog/mobile-app-update-strategies-a-developers-checklist/',
  '/blog/monitoreo-de-actualizaciones-ota-en-aplicaciones-capacitor': '/blog/monitor-ota-updates-in-capacitor-apps/',
  '/blog/métadonnées-app-store-ce-que-les-développeurs-doivent-savoir': '/blog/app-store-metadata-what-developers-must-know/',
  '/blog/normes-de-securite-des-api-principales-pour-la-conformite-de-l-app-store': '/blog/top-api-security-standards-for-app-store-compliance/',
  '/blog/npm-scripts-für-capacitor-ota-updates-erklärt': '/blog/npm-scripts-for-capacitor-ota-updates-explained/',
  '/blog/nutzerzustimmung-für-ota-updates-best-practices': '/blog/user-consent-for-ota-updates-best-practices/',
  '/blog/opciones-del-complemento-capacitor-para-actualizaciones-ota': '/blog/capacitor-plugin-options-for-ota-updates/',
  '/blog/Open-Source vs proprietäre App-Update-Lösungen': '/blog/open-source-vs-proprietary-app-update-solutions/',
  '/blog/options-du-plugin-capacitor-pour-les-mises-a-jour-ota': '/blog/capacitor-plugin-options-for-ota-updates/',
  '/blog/opzioni-hosting-cloud-aggiornamenti-ota-capacitor-confrontate': '/blog/capacitor-ota-updates-cloud-hosting-options-compared/',
  '/blog/opzioni-plugin-capacitor-per-aggiornamenti-ota': '/blog/capacitor-plugin-options-for-ota-updates/',
  '/blog/ota-updates-im-beta-zustand-richtlinienkonform-bleiben': '/blog/ota-updates-in-beta-staying-policy-compliant/',
  '/blog/perche-la-gestione-del-consenso-e-importante-per-la-conformita-delle-app': '/blog/why-consent-management-matters-for-app-compliance/',
  '/blog/plugin-base-native-bridge-android-di-capacitor': '/blog/capacitor-native-bridge-android-plugin-basics/',
  '/blog/prassi-consigliate-per-gli-aggiornamenti-ota-di-staging': '/blog/staging-ota-updates-best-practices/',
  '/blog/pratiques-recommandees-ui-ux-multiplateforme-pour-les-applications-capacitor': '/blog/cross-platform-uiux-best-practices-for-capacitor-apps/',
  "/blog/pratiques-recommandées-pour-l'intégration-cicd-appflow": '/blog/appflow-cicd-integration-best-practices/',
  '/blog/Preisreduzierung bei Capgo': '/blog/capgo-price-reduction/',
  '/blog/problemes-frequents-dans-le-pipeline-cicd-pour-les-mises-a-jour-ota': '/blog/common-cicd-bottlenecks-in-ota-pipelines/',
  '/blog/problemi-comuni-e-soluzioni-di-aggiornamenti-live-per-sviluppatori': '/blog/common-live-update-issues-and-solutions-for-developers/',
  '/blog/protection-confidentialite-apple-google-conformite-donnees-tierces': '/blog/apple-vs-google-privacy-compliance-for-third-party-data/',
  '/blog/Pruebas de actualizaciones OTA de Capacitor': '/blog/testing-capacitor-ota-updates/',
  '/blog/pruebas-de-cumplimiento-en-cicd-para-apps-capacitor': '/blog/compliance-checks-in-cicd-for-capacitor-apps/',
  '/blog/Reducción de precios en Capgo': '/blog/capgo-price-reduction/',
  '/blog/regole-di-privacy-apple-per-app-capacitor': '/blog/apple-privacy-rules-for-capacitor-apps/',
  '/blog/rollback-mechanismen-in-capacitor-plugins': '/blog/rollback-mechanisms-in-capacitor-plugins/',
  '/blog/rollback-strategien-für-capacitor-live-updates': '/blog/rollback-strategies-for-capacitor-live-updates/',
  '/blog/rollback-strategien-für-cicd-workflows': '/blog/rollback-strategies-for-cicd-workflows/',
  '/blog/rollout-graduali-per-aggiornamenti-live-di-capacitor': '/blog/phased-rollouts-for-capacitor-live-updates/',
  "/blog/règles-de-confidentialité-d'apple-pour-les-applications-capacitor": '/blog/apple-privacy-rules-for-capacitor-apps/',
  '/blog/schlüsselverwaltung-unter-chinas-verschlüsselungsvorschriften': '/blog/key-management-under-chinas-encryption-rules/',
  '/blog/seguridad-de-la-pipeline-para-apps-de-capacitor-conclusiones-importantes': '/blog/pipeline-security-for-capacitor-apps-key-insights/',
  '/blog/selbst-gehostete-live-updates': '/blog/self-hosted-live-updates/',
  '/blog/setup-ci-und-cd-gitlab': '/blog/setup-ci-and-cd-in-gitlab/',
  '/blog/sicherheit-der-pipeline-für-capacitor-apps-wichtige-erkenntnisse': '/blog/pipeline-security-for-capacitor-apps-key-insights/',
  '/blog/sicherheits-checkliste-für-ota-updates-in-capacitor-apps': '/blog/ota-security-checklist-for-capacitor-apps/',
  '/blog/sicurezza-della-chiave-api-per-la-conformità-con-app-store': '/blog/api-key-security-for-app-store-compliance/',
  '/blog/So fügen Sie Plugins von Drittanbietern in Capacitor-Apps hinzu': '/blog/how-to-add-third-party-plugins-in-capacitor-apps/',
  '/blog/so-funktionieren-die-gestaffelten-google-play-rollouts': '/blog/google-play-staged-rollouts-how-it-works/',
  '/blog/so-passen-sie-build-skripte-mit-capacitor-cli-an': '/blog/how-to-customize-build-scripts-with-capacitor-cli/',
  '/blog/so-verwenden-sie-die-capacitor-cli-für-ota-updates': '/blog/how-to-use-capacitor-cli-for-ota-updates/',
  '/blog/so-werden-ota-updates-mit-schlüsselverwaltung-gesichert': '/blog/how-to-secure-ota-updates-with-key-management/',
  "/blog/Solutions de mise à jour d'applications open source vs propriétaires": '/blog/open-source-vs-proprietary-app-update-solutions/',
  '/blog/standard-di-sicurezza-api-per-conformita-app-store': '/blog/top-api-security-standards-for-app-store-compliance/',
  '/blog/strategie-di-ripristino-per-gli-aggiornamenti-live-di-capacitor': '/blog/rollback-strategies-for-capacitor-live-updates/',
  '/blog/stratégies-de-restauration-pour-les-workflows-cicd': '/blog/rollback-strategies-for-cicd-workflows/',
  '/blog/strumenti-migliori-per-il-debugging-degli-aggiornamenti-ota-in-capacitor': '/blog/top-tools-for-debugging-ota-updates-in-capacitor/',
  '/blog/suggerimenti-sulla-sicurezza-degli-aggiornamenti-ota-capacitor': '/blog/capacitor-ota-updates-security-tips/',
  '/blog/Testen von Capacitor OTA-Updates': '/blog/testing-capacitor-ota-updates/',
  '/blog/testing-gli-aggiornamenti-ota-di-capacitor-con-scenari-di-prova': '/blog/testing-capacitor-ota-updates-with-mock-scenarios/',
  '/blog/testing-von-capacitor-ota-updates-mit-mock-szenarien': '/blog/testing-capacitor-ota-updates-with-mock-scenarios/',
  '/blog/top-6-tools-fuer-app-aktualisierungen-management-in-2025': '/blog/top-6-tools-for-managing-app-updates-in-2025/',
  '/blog/top-api-security-standards-für-app-store-konformität': '/blog/top-api-security-standards-for-app-store-compliance/',
  '/blog/top-tools-für-das-debugging-von-plattformspezifischem-code-in-capacitor': '/blog/top-tools-for-debugging-platform-specific-code-in-capacitor/',
  '/blog/transferencia-de-datos-de-web-a-android-con-el-puente-nativo-de-capacitor': '/blog/capacitor-native-bridge-web-to-android-data-transfer/',
  '/blog/ultimative-anleitung-für-app-store-konforme-ota-updates': '/blog/ultimate-guide-to-app-store-compliant-ota-updates/',
  '/blog/update-ihrer-capacitor-anwendungen-nahtlos-mit-capacitor-updater': '/blog/update-your-capacitor-apps-seamlessly-using-capacitor-updater/',
  '/blog/Verificación de integridad para actualizaciones de Capacitor': '/blog/integrity-checks-for-capacitor-updates/',
  '/blog/versioning-delle-app-in-capacitor': '/blog/version-tagging-in-capacitor-apps/',
  '/blog/Versionsunterschiede zwischen Capacitor und Appflow': '/blog/capacitor-vs-appflow-versioning-differences/',
  '/blog/verwaltung-von-geheimnissen-in-cicd-pipelines': '/blog/managing-secrets-in-cicd-pipelines/',
  '/blog/von-microsoft-app-center-zu-capgo': '/blog/moving-from-microsoft-app-center-to-capgo/',
  '/blog/warum-einwilligungsmanagement-für-app-konformität-wichtig-ist': '/blog/why-consent-management-matters-for-app-compliance/',
  '/blog/Was Entwickler über App Store Metadaten wissen müssen': '/blog/app-store-metadata-what-developers-must-know/',
  '/blog/Was Sie über Capacitor-Plugins wissen müssen': '/blog/capacitor-plugins-what-you-need-to-know/',
  '/blog/Wie Capacitor Plattform-Unterschiede handhabt': '/blog/how-capacitor-handles-platform-differences/',
  '/blog/wie-capacitor-web-und-nativen-code-verbindet': '/blog/how-capacitor-bridges-web-and-native-code/',
  '/blog/wie-chinas-datenschutzgesetze-die-app-store-einreichungen-beeinflussen': '/blog/how-chinas-data-laws-impact-app-store-submissions/',
  '/blog/wie-cicd-tools-ota-updates-auslösen': '/blog/how-cicd-tools-trigger-ota-updates/',
  '/blog/wie-delta-updates-die-payload-größe-reduzieren': '/blog/how-delta-updates-reduce-payload-size/',
  '/blog/wie-die-native-bridge-in-capacitor-android-apps-funktioniert': '/blog/how-native-bridge-works-in-capacitor-android-apps/',
  '/blog/wie-ende-zu-ende-verschlüsselung-updates-sichert': '/blog/how-end-to-end-encryption-secures-updates/',
  '/blog/wie-fuegt-man-abhaengigkeiten-in-capacitor-plugins-hinzu': '/blog/how-to-add-dependencies-in-capacitor-plugins/',
  '/blog/wie-man-aar-dateien-in-capacitor-plugins-verwendet': '/blog/how-to-use-aar-files-in-capacitor-plugins/',
  '/blog/wie-man-benutzeranfragen-nach-ccpa-verarbeitet': '/blog/how-to-handle-user-data-requests-under-ccpa/',
  '/blog/wie-man-benutzerdaten-in-capacitor-apps-verwaltet': '/blog/how-to-handle-user-data-in-capacitor-apps/',
  '/blog/wie-man-die-capgo-dokumentation-für-ota-updates-verwendet': '/blog/how-to-use-capgo-documentation-for-ota-updates/',
  '/blog/wie-man-geolokalisierung-für-ota-updates-hinzufügt': '/blog/how-to-add-geolocation-targeting-to-ota-updates/',
  '/blog/wie-man-ota-update-erfolge-in-capacitor-apps-verfolgt': '/blog/how-to-track-ota-update-success-in-capacitor-apps/',
  '/blog/wie-man-ota-updates-für-capacitor-apps-plant': '/blog/how-to-schedule-ota-updates-for-capacitor-apps/',
  '/blog/wie-man-semantic-versioning-mit-capgo-ota-updates-verwendet': '/blog/how-to-use-semantic-versioning-with-capgo-ota-updates/',
  '/blog/wie-mobile-apps-die-datenschutzgesetze-der-usa-einhalten': '/blog/how-mobile-apps-stay-compliant-with-us-privacy-laws/',
  '/blog/wie-rbac-ota-updates-in-capacitor-apps-absichert': '/blog/how-rbac-secures-ota-updates-in-capacitor-apps/',
  '/blog/wie-segmentieren-sie-benutzer-nach-plan-und-kanälen': '/blog/how-to-segment-users-by-plan-and-channels/',
  '/blog/wie-sich-das-chinesische-cybersicherheitsgesetz-auf-app-entwickler-auswirkt': '/blog/how-chinas-cybersecurity-law-impacts-app-developers/',
  '/blog/wie-sich-die-durchsetzung-des-ccpa-auf-apps-auswirkt': '/blog/how-ccpa-enforcement-impacts-apps/',
  '/blog/wie-sich-ota-updates-auf-die-app-store-sicherheit-auswirken': '/blog/how-ota-updates-affect-app-store-security/',
  '/blog/zahlungsdaten-sicherheit-fuer-app-store-genehmigung': '/blog/payment-data-security-for-app-store-approval/',
}

function normalizeLegacyLookupPath(pathname: string): string {
  if (pathname.length > 1 && pathname.endsWith('/')) return pathname.slice(0, -1)
  return pathname
}

function decodePathnameForLookup(pathname: string): string {
  try {
    return decodeURIComponent(pathname)
  } catch {
    return pathname
  }
}

/** Returns a canonical target path when `pathname` is a known legacy alias. */
export function resolveLegacyPathRedirect(pathname: string): string | null {
  // URL.pathname is percent-encoded; map keys use decoded Unicode / spaces.
  const key = normalizeLegacyLookupPath(decodePathnameForLookup(pathname))
  return LEGACY_PATH_REDIRECTS[key] ?? null
}
