// Do not edit this file
// Auto-generated from generate_translation_ts_file.tsx code
export const locales = ["de","en","es","fr","id","it","jp","ko"]
export type Locales = "de" | "en" | "es" | "fr" | "id" | "it" | "jp" | "ko"
export const defaultLocale = 'en'