// Do not edit this file
// Auto-generated from generate_translation_ts_file.tsx code
export const locales = ["en","es","fr"]
export type Locales = "en" | "es" | "fr"
export const defaultLocale = 'en'