export interface Action {
  icon?: string
  href: string
  title: string
  name?: string
  author: string
  description: string
  iconForeground?: string
  iconBackground?: string
}

export interface Plugin extends Action {
  npmDownloads?: number
  githubStars?: number
  readme?: string
  datePublished?: string
  dateModified?: string
  tutorial?: string
  locale?: string
}

export const actions = [
  {
    name: '@capgo/native-market',
    author: 'github.com/Cap-go',
    description: 'Deep link users directly to your app page on Google Play Store or Apple App Store',
    href: 'https://github.com/Cap-go/capacitor-native-market/',
    title: 'Native Market',
    icon: 'ArchiveBoxArrowDown',
  },
  {
    name: '@capgo/capacitor-native-biometric',
    author: 'github.com/Cap-go',
    description: 'Secure authentication using Face ID, Touch ID, and Android biometric APIs',
    href: 'https://github.com/Cap-go/capacitor-native-biometric/',
    title: 'Native Biometric',
    icon: 'FingerPrint',
  },
  {
    name: '@capgo/camera-preview',
    author: 'github.com/Cap-go',
    description: 'Display live camera feed as overlay with customizable controls and capture capabilities',
    href: 'https://github.com/Cap-go/capacitor-camera-preview/',
    title: 'Camera Preview',
    icon: 'Camera',
  },
  {
    name: '@capgo/capacitor-updater',
    author: 'github.com/Cap-go',
    description: 'Deploy live updates instantly to your users without app store review delays',
    href: 'https://github.com/Cap-go/capacitor-updater/',
    title: 'Updater',
    icon: 'ArrowPath',
  },
  {
    name: '@capgo/capacitor-uploader',
    author: 'github.com/Cap-go',
    description: 'Upload large files reliably in background with progress tracking and retry support',
    href: 'https://github.com/Cap-go/capacitor-uploader/',
    title: 'Uploader',
    icon: 'ArrowUpOnSquare',
  },
  {
    name: '@revenuecat/purchases-capacitor',
    author: 'github.com/Cap-go',
    description: 'Implement in-app subscriptions and purchases with RevenueCat SDK for cross-platform monetization',
    href: 'https://github.com/RevenueCat/purchases-capacitor/',
    title: 'Purchases',
    icon: 'CurrencyDollar',
  },
  {
    name: '@capgo/capacitor-flash',
    author: 'github.com/Cap-go',
    description: 'Control device flashlight and torch with simple on/off toggle functionality',
    href: 'https://github.com/Cap-go/capacitor-flash/',
    title: 'Flash',
    icon: 'Bolt',
  },
  {
    name: '@capgo/capacitor-screen-recorder',
    author: 'github.com/Cap-go',
    description: 'Capture screen recordings with audio for tutorials, demos, and bug reports',
    href: 'https://github.com/Cap-go/capacitor-screen-recorder/',
    title: 'Screen Recorder',
    icon: 'VideoCamera',
  },
  {
    name: '@capgo/capacitor-crisp',
    author: 'github.com/Cap-go',
    description: 'Integrate Crisp live chat and customer support directly into your mobile app',
    href: 'https://github.com/Cap-go/capacitor-crisp/',
    title: 'Crisp',
    icon: 'ChatBubbleLeft',
  },
  {
    name: '@capgo/capacitor-intercom',
    author: 'github.com/Cap-go',
    description: 'Integrate Intercom live chat, help center, and support workflows in your Capacitor app',
    href: 'https://github.com/Cap-go/capacitor-intercom/',
    title: 'Intercom',
    icon: 'ChatBubbleLeft',
  },
  {
    name: '@capgo/nativegeocoder',
    author: 'github.com/Cap-go',
    description: 'Convert addresses to coordinates and coordinates to addresses using native geocoding',
    href: 'https://github.com/Cap-go/capacitor-nativegeocoder/',
    title: 'Native Geocoder',
    icon: 'MapPin',
  },
  {
    name: '@capgo/inappbrowser',
    author: 'github.com/Cap-go',
    description: 'Open web pages in a customizable in-app browser without leaving your application',
    href: 'https://github.com/Cap-go/capacitor-inappbrowser/',
    title: 'In App Browser',
    icon: 'GlobeAlt',
  },
  {
    name: '@capgo/capacitor-mqtt',
    author: 'github.com/Cap-go',
    description: 'MQTT support for real-time messaging across iOS, Android, and Web.',
    href: 'https://github.com/Cap-go/capacitor-mqtt/',
    title: 'MQTT',
    icon: 'Signal',
  },
  {
    name: '@capgo/capacitor-mute',
    author: 'github.com/Cap-go',
    description: 'Detect device mute switch state for iOS devices to handle audio playback appropriately',
    href: 'https://github.com/Cap-go/capacitor-mute/',
    title: 'Mute',
    icon: 'SpeakerXMark',
  },
  {
    name: '@capgo/native-audio',
    author: 'github.com/Cap-go',
    description: 'Play short audio files with low latency using native audio engine for games and apps',
    href: 'https://github.com/Cap-go/capacitor-native-audio/',
    title: 'Native Audio',
    icon: 'SpeakerWave',
  },
  {
    name: '@capgo/capacitor-shake',
    author: 'github.com/Cap-go',
    description: 'Detect shake gestures on device for triggering actions like undo or feedback',
    href: 'https://github.com/Cap-go/capacitor-shake/',
    title: 'Shake',
    icon: 'DevicePhoneMobile',
  },
  {
    name: '@capgo/capacitor-navigation-bar',
    author: 'github.com/Cap-go',
    description: 'Customize Android navigation bar color and visibility for immersive UI experiences',
    href: 'https://github.com/Cap-go/capacitor-navigation-bar/',
    title: 'Navigation Bar',
    icon: 'Bars3',
  },
  {
    name: '@capgo/ivs-player',
    author: 'github.com/Cap-go',
    description: 'Stream ultra-low latency live video using Amazon Interactive Video Service (IVS)',
    href: 'https://github.com/Cap-go/capacitor-ivs-player/',
    title: 'IVS Player',
    icon: 'PlayCircle',
  },
  {
    name: '@capgo/home-indicator',
    author: 'github.com/Cap-go',
    description: 'Hide or show iOS home indicator for fullscreen and immersive app experiences',
    href: 'https://github.com/Cap-go/capacitor-home-indicator/',
    title: 'Indicator',
    icon: 'Home',
  },
  {
    name: '@capgo/native-purchases',
    author: 'github.com/Cap-go',
    description: 'Implement native in-app purchases and subscriptions for iOS and Android with simple API',
    href: 'https://github.com/Cap-go/capacitor-native-purchases/',
    title: 'Native Purchases',
    icon: 'CurrencyDollar',
  },
  {
    name: '@capgo/capacitor-data-storage-sqlite',
    author: 'github.com/Cap-go',
    description: 'Store data locally using SQLite database with simple key-value API and encryption support',
    href: 'https://github.com/Cap-go/capacitor-data-storage-sqlite/',
    title: 'Data Storage',
    icon: 'CircleStack',
  },
  {
    name: '@capgo/capacitor-android-usagestatsmanager',
    author: 'github.com/Cap-go',
    description: 'Access Android usage statistics to track app usage time and screen time analytics',
    href: 'https://github.com/Cap-go/capacitor-android-usagestatsmanager/',
    title: 'Usage Stats Manager',
    icon: 'ChartBar',
  },
  {
    name: '@capgo/capacitor-streamcall',
    author: 'github.com/Cap-go',
    description: 'Integrate video calling and live streaming with Stream SDK for real-time communication',
    href: 'https://github.com/Cap-go/capacitor-streamcall/',
    title: 'Streamcall',
    icon: 'VideoCamera',
  },
  {
    name: '@capgo/capacitor-autofill-save-password',
    author: 'github.com/Cap-go',
    description: 'Prompt users to save passwords to device autofill for seamless login experience',
    href: 'https://github.com/Cap-go/capacitor-autofill-save-password/',
    title: 'Autofill Save Password',
    icon: 'UserCircle',
  },
  {
    name: '@capgo/capacitor-social-login',
    author: 'github.com/Cap-go',
    description: 'Authenticate users with Google, Facebook, and Apple Sign-In for easy social login',
    href: 'https://github.com/Cap-go/capacitor-social-login/',
    title: 'Social Login',
    icon: 'UserCircle',
  },
  {
    name: '@capgo/capacitor-jw-player',
    author: 'github.com/Cap-go',
    description: 'Embed JW Player for professional video streaming with ads and analytics support',
    href: 'https://github.com/Cap-go/capacitor-jw-player/',
    title: 'JW Player',
    icon: 'PlayCircle',
  },
  {
    name: '@capgo/capacitor-ricoh360-camera-plugin',
    author: 'github.com/Cap-go',
    description: 'Control Ricoh Theta 360-degree cameras for immersive panoramic photography',
    href: 'https://github.com/Cap-go/capacitor-ricoh360-camera-plugin/',
    title: 'Ricoh360 Camera',
    icon: 'Camera',
  },
  {
    name: '@capgo/capacitor-admob',
    author: 'github.com/Cap-go',
    description: 'Monetize your app with Google AdMob banner, interstitial, and rewarded ads',
    href: 'https://github.com/Cap-go/capacitor-admob/',
    title: 'AdMob',
    icon: 'Megaphone',
  },
  {
    name: '@capgo/capacitor-alarm',
    author: 'github.com/Cap-go',
    description: 'Schedule native alarms and notifications even when app is closed',
    href: 'https://github.com/Cap-go/capacitor-alarm/',
    title: 'Alarm',
    icon: 'Bell',
  },
  {
    name: '@capgo/capacitor-android-inline-install',
    author: 'github.com/Cap-go',
    description: 'Install app updates directly within the app without leaving to Play Store',
    href: 'https://github.com/Cap-go/capacitor-android-inline-install/',
    title: 'Android Inline Install',
    icon: 'CloudArrowDown',
  },
  {
    name: '@capgo/capacitor-android-kiosk',
    author: 'github.com/Cap-go',
    description: 'Lock Android devices into kiosk mode with launcher functionality and hardware key control',
    href: 'https://github.com/Cap-go/capacitor-android-kiosk/',
    title: 'Android Kiosk',
    icon: 'LockClosed',
  },
  {
    name: '@capgo/capacitor-appinsights',
    author: 'github.com/Cap-go',
    description: 'Track app usage, performance metrics, and user behavior with Apptopia AppInsights',
    href: 'https://github.com/Cap-go/capacitor-appinsights/',
    title: 'AppInsights',
    icon: 'ChartBar',
  },
  {
    name: '@capgo/capacitor-app-attest',
    author: 'github.com/Cap-go',
    description: 'Capacitor plugin for cross-platform device attestation using Apple App Attest and Google Play Integrity Standard',
    href: 'https://github.com/Cap-go/capacitor-app-attest/',
    title: 'App Attest',
    icon: 'ShieldCheck',
  },
  {
    name: '@capgo/capacitor-audiosession',
    author: 'github.com/Cap-go',
    description: 'Configure iOS audio session for background playback, mixing, and routing control',
    href: 'https://github.com/Cap-go/capacitor-audiosession/',
    title: 'Audio Session',
    icon: 'SpeakerWave',
  },
  {
    name: '@capgo/capacitor-background-geolocation',
    author: 'github.com/Cap-go',
    description: 'Track device location continuously in background with battery-efficient geofencing',
    href: 'https://github.com/Cap-go/capacitor-background-geolocation/',
    title: 'Background Geolocation',
    icon: 'MapPin',
  },
  {
    name: '@capgo/capacitor-document-scanner',
    author: 'github.com/Cap-go',
    description: 'Scan documents with auto edge detection, perspective correction, and PDF export',
    href: 'https://github.com/Cap-go/capacitor-document-scanner/',
    title: 'Document Scanner',
    icon: 'Document',
  },
  {
    name: '@capgo/capacitor-downloader',
    author: 'github.com/Cap-go',
    description: 'Download large files in background with progress tracking and pause/resume support',
    href: 'https://github.com/Cap-go/capacitor-downloader/',
    title: 'Downloader',
    icon: 'CloudArrowDown',
  },
  {
    name: '@capgo/capacitor-env',
    author: 'github.com/Cap-go',
    description: 'Securely manage environment variables and configuration across different build environments',
    href: 'https://github.com/Cap-go/capacitor-env/',
    title: 'Env',
    icon: 'Cog',
  },
  {
    name: '@capgo/capacitor-ffmpeg',
    author: 'github.com/Cap-go',
    description: 'Video encoding and processing powered by FFmpeg for compression and conversion',
    href: 'https://github.com/Cap-go/capacitor-ffmpeg/',
    title: 'FFmpeg',
    icon: 'VideoCamera',
  },
  {
    name: '@capgo/capacitor-gtm',
    author: 'github.com/Cap-go',
    description: 'Google Tag Manager integration for analytics and tracking',
    href: 'https://github.com/Cap-go/capacitor-gtm/',
    title: 'GTM',
    icon: 'ChartBar',
  },
  {
    name: '@capgo/capacitor-health',
    author: 'github.com/Cap-go',
    description: 'Access health and fitness data from native health platforms',
    href: 'https://github.com/Cap-go/capacitor-health/',
    title: 'Health',
    icon: 'Heart',
  },
  {
    name: '@capgo/capacitor-is-root',
    author: 'github.com/Cap-go',
    description: 'Detect rooted Android or jailbroken iOS devices to enhance app security',
    href: 'https://github.com/Cap-go/capacitor-is-root/',
    title: 'Is Root',
    icon: 'ShieldCheck',
  },
  {
    name: '@capgo/capacitor-app-tracking-transparency',
    author: 'github.com/Cap-go',
    description: 'Request and check iOS App Tracking Transparency permission for IDFA access',
    href: 'https://github.com/Cap-go/capacitor-app-tracking-transparency/',
    title: 'App Tracking Transparency',
    icon: 'EyeSlash',
  },
  {
    name: '@capgo/capacitor-launch-navigator',
    author: 'github.com/Cap-go',
    description: 'Open navigation apps like Google Maps or Apple Maps with directions to destinations',
    href: 'https://github.com/Cap-go/capacitor-launch-navigator/',
    title: 'Launch Navigator',
    icon: 'Map',
  },
  {
    name: '@capgo/capacitor-live-reload',
    author: 'github.com/Cap-go',
    description: 'Connect to your dev server for instant hot reloading during development',
    href: 'https://github.com/Cap-go/capacitor-live-reload/',
    title: 'Live Reload',
    icon: 'RocketLaunch',
  },
  {
    name: '@capgo/capacitor-llm',
    author: 'github.com/Cap-go',
    description: 'Run Large Language Models locally on-device with Apple Intelligence and MLX support',
    href: 'https://github.com/Cap-go/capacitor-llm/',
    title: 'LLM',
    icon: 'CpuChip',
  },
  {
    name: '@capgo/capacitor-media-session',
    author: 'github.com/Cap-go',
    description: 'Control media playback from lock screen and notification center',
    href: 'https://github.com/Cap-go/capacitor-media-session/',
    title: 'Media Session',
    icon: 'PlayCircle',
  },
  {
    name: '@capgo/capacitor-mux-player',
    author: 'github.com/Cap-go',
    description: 'Stream adaptive bitrate video with Mux player for optimized playback quality',
    href: 'https://github.com/Cap-go/capacitor-mux-player/',
    title: 'Mux Player',
    icon: 'PlayCircle',
  },
  {
    name: '@capgo/capacitor-pay',
    author: 'github.com/Cap-go',
    description: 'Accept payments with Apple Pay and Google Pay for seamless checkout experience',
    href: 'https://github.com/Cap-go/capacitor-pay/',
    title: 'Pay',
    icon: 'CreditCard',
  },
  {
    name: '@capgo/capacitor-pdf-generator',
    author: 'github.com/Cap-go',
    description: 'Create PDF documents from HTML templates for invoices, reports, and receipts',
    href: 'https://github.com/Cap-go/capacitor-pdf-generator/',
    title: 'PDF Generator',
    icon: 'DocumentText',
  },
  {
    name: '@capgo/capacitor-persistent-account',
    author: 'github.com/Cap-go',
    description: 'Preserve user authentication and account data across app reinstalls and updates',
    href: 'https://github.com/Cap-go/capacitor-persistent-account/',
    title: 'Persistent Account',
    icon: 'UserCircle',
  },
  {
    name: '@capgo/capacitor-photo-library',
    author: 'github.com/Cap-go',
    description: 'Browse, save, and manage photos and videos in device photo library with permissions',
    href: 'https://github.com/Cap-go/capacitor-photo-library/',
    title: 'Photo Library',
    icon: 'Photo',
  },
  {
    name: '@capgo/capacitor-sim',
    author: 'github.com/Cap-go',
    description: 'Retrieve SIM card information including carrier name, country code, and phone number',
    href: 'https://github.com/Cap-go/capacitor-sim/',
    title: 'SIM',
    icon: 'Signal',
  },
  {
    name: '@capgo/capacitor-speech-recognition',
    author: 'github.com/Cap-go',
    description: 'Natural, low-latency speech recognition with streaming partial results and cross-platform parity',
    href: 'https://github.com/Cap-go/capacitor-speech-recognition/',
    title: 'Speech Recognition',
    icon: 'Microphone',
  },
  {
    name: '@capgo/capacitor-textinteraction',
    author: 'github.com/Cap-go',
    description: 'Enable advanced text selection, copy-paste, and interaction features in web views',
    href: 'https://github.com/Cap-go/capacitor-textinteraction/',
    title: 'Text Interaction',
    icon: 'DocumentText',
  },
  {
    name: '@capgo/capacitor-twilio-voice',
    author: 'github.com/Cap-go',
    description: 'Make and receive VoIP calls with Twilio Voice for in-app calling functionality',
    href: 'https://github.com/Cap-go/capacitor-twilio-voice/',
    title: 'Twilio Voice',
    icon: 'Phone',
  },
  {
    name: '@capgo/capacitor-video-player',
    author: 'github.com/Cap-go',
    description: 'Native video playback with subtitles, fullscreen, and comprehensive controls',
    href: 'https://github.com/Cap-go/capacitor-video-player/',
    title: 'Video Player',
    icon: 'PlayCircle',
  },
  {
    name: '@capgo/capacitor-volume-buttons',
    author: 'github.com/Cap-go',
    description: 'Capture hardware volume button presses for custom app controls and shortcuts',
    href: 'https://github.com/Cap-go/capacitor-volume-buttons/',
    title: 'Volume Buttons',
    icon: 'SpeakerWave',
  },
  {
    name: '@capgo/capacitor-youtube-player',
    author: 'github.com/Cap-go',
    description: 'Embed YouTube videos with full player API control and event handling',
    href: 'https://github.com/Cap-go/capacitor-youtube-player/',
    title: 'YouTube Player',
    icon: 'PlayCircle',
  },
  {
    name: '@capgo/capacitor-wechat',
    author: 'github.com/Cap-go',
    description: 'WeChat SDK for Capacitor - enables authentication, sharing, payments, and mini-programs',
    href: 'https://github.com/Cap-go/capacitor-wechat/',
    title: 'WeChat',
    icon: 'ChatBubbleOvalLeft',
  },
  {
    name: '@capgo/capacitor-ibeacon',
    author: 'github.com/Cap-go',
    description: 'iBeacon plugin for Capacitor - proximity detection and beacon region monitoring',
    href: 'https://github.com/Cap-go/capacitor-ibeacon/',
    title: 'iBeacon',
    icon: 'Radio',
  },
  {
    name: '@capgo/capacitor-nfc',
    author: 'github.com/Cap-go',
    description: 'Native NFC tag discovery, reading and writing for Capacitor apps on iOS and Android',
    href: 'https://github.com/Cap-go/capacitor-nfc/',
    title: 'NFC',
    icon: 'Tag',
  },
  {
    name: '@capgo/capacitor-age-range',
    author: 'github.com/Cap-go',
    description: 'Cross-platform age range detection using Google Play Age Signals (Android) and Apple DeclaredAgeRange (iOS)',
    href: 'https://github.com/Cap-go/capacitor-age-range/',
    title: 'Age Range',
    icon: 'UserGroup',
  },
  {
    name: '@capgo/capacitor-persona',
    author: 'github.com/Cap-go',
    description: 'Launch Persona identity verification inquiries with native iOS and Android SDKs',
    href: 'https://github.com/Cap-go/capacitor-persona/',
    title: 'Persona',
    icon: 'UserCircle',
  },
  {
    name: '@capgo/capacitor-android-age-signals',
    author: 'github.com/Cap-go',
    description: 'Google Play Age Signals API wrapper - detect supervised accounts and verified users',
    href: 'https://github.com/Cap-go/capacitor-android-age-signals/',
    title: 'Age Signals',
    icon: 'UserGroup',
  },
  {
    name: '@capgo/capacitor-barometer',
    author: 'github.com/Cap-go',
    description: 'Access device barometer for atmospheric pressure and altitude readings',
    href: 'https://github.com/Cap-go/capacitor-barometer/',
    title: 'Barometer',
    icon: 'ChartBar',
  },
  {
    name: '@capgo/capacitor-accelerometer',
    author: 'github.com/Cap-go',
    description: 'Read device accelerometer for motion detection and orientation tracking',
    href: 'https://github.com/Cap-go/capacitor-accelerometer/',
    title: 'Accelerometer',
    icon: 'ArrowsPointingOut',
  },
  {
    name: '@capgo/capacitor-contacts',
    author: 'github.com/Cap-go',
    description: 'Access and manage device contacts with read and write capabilities',
    href: 'https://github.com/Cap-go/capacitor-contacts/',
    title: 'Contacts',
    icon: 'UserGroup',
  },
  {
    name: '@capgo/capacitor-audio-recorder',
    author: 'github.com/Cap-go',
    description: 'Record audio on iOS, Android, and Web with simple controls and formats',
    href: 'https://github.com/Cap-go/capacitor-audio-recorder/',
    title: 'Audio Recorder',
    icon: 'Microphone',
  },
  {
    name: '@capgo/capacitor-share-target',
    author: 'github.com/Cap-go',
    description: 'Receive shared content from other apps - text, images, and files',
    href: 'https://github.com/Cap-go/capacitor-share-target/',
    title: 'Share Target',
    icon: 'Share',
  },
  {
    name: '@capgo/capacitor-realtimekit',
    author: 'github.com/Cap-go',
    description: 'Cloudflare Calls integration with built-in UI for video meetings and real-time communication',
    href: 'https://github.com/Cap-go/capacitor-realtimekit/',
    title: 'RealtimeKit',
    icon: 'VideoCamera',
  },
  {
    name: '@capgo/capacitor-pedometer',
    author: 'github.com/Cap-go',
    description: 'Track steps, distance, pace, cadence, and floors with device pedometer sensors',
    href: 'https://github.com/Cap-go/capacitor-pedometer/',
    title: 'Pedometer',
    icon: 'Signal',
  },
  {
    name: '@capgo/capacitor-fast-sql',
    author: 'github.com/Cap-go',
    description: 'High-performance native SQLite with custom protocol for efficient sync operations and IndexedDB replacement',
    href: 'https://github.com/Cap-go/capacitor-fast-sql/',
    title: 'Fast SQL',
    icon: 'CircleStack',
  },
  {
    name: '@capgo/capacitor-file-compressor',
    author: 'github.com/Cap-go',
    description: 'Capacitor plugin for efficient image compression supporting PNG, JPEG, and WebP formats across iOS, Android, and Web platforms',
    href: 'https://github.com/Cap-go/capacitor-file-compressor/',
    title: 'File Compressor',
    icon: 'Photo',
  },
  {
    name: '@capgo/capacitor-speech-synthesis',
    author: 'github.com/Cap-go',
    description: 'Synthesize speech from text with full control over language, voice, pitch, rate, and volume.',
    href: 'https://github.com/Cap-go/capacitor-speech-synthesis/',
    title: 'Speech Synthesis',
    icon: 'SpeakerWave',
  },
  {
    name: '@capgo/capacitor-printer',
    author: 'github.com/Cap-go',
    description: 'Capacitor plugin for printing documents, HTML, PDFs, images and web views',
    href: 'https://github.com/Cap-go/capacitor-printer/',
    title: 'Printer',
    icon: 'Printer',
  },
  {
    name: '@capgo/capacitor-zip',
    author: 'github.com/Cap-go',
    description: 'A free Capacitor plugin for zipping and unzipping files on iOS, Android, and Web.',
    href: 'https://github.com/Cap-go/capacitor-zip/',
    title: 'Zip',
    icon: 'ArchiveBox',
  },
  {
    name: '@capgo/capacitor-wifi',
    author: 'github.com/Cap-go',
    description: 'Manage WiFi connectivity for your Capacitor app',
    href: 'https://github.com/Cap-go/capacitor-wifi/',
    title: 'WiFi',
    icon: 'Wifi',
  },
  {
    name: '@capgo/capacitor-screen-orientation',
    author: 'github.com/Cap-go',
    description: 'Screen orientation plugin with support for bypassing orientation lock',
    href: 'https://github.com/Cap-go/capacitor-screen-orientation/',
    title: 'Screen Orientation',
    icon: 'DevicePhoneMobile',
  },
  {
    name: '@capgo/capacitor-webview-guardian',
    author: 'github.com/Cap-go',
    description: 'Detect when the WebView was killed in the background and relaunch it on foreground',
    href: 'https://github.com/Cap-go/capacitor-webview-guardian/',
    title: 'WebView Guardian',
    icon: 'ShieldExclamation',
  },
  {
    name: '@capgo/capacitor-webview-version-checker',
    author: 'github.com/Cap-go',
    description:
      'Capacitor plugin for checking Android WebView version freshness and guiding users to native update flows',
    href: 'https://github.com/Cap-go/capacitor-webview-version-checker/',
    title: 'WebView Version Checker',
    icon: 'ShieldExclamation',
  },
  {
    name: '@capgo/capacitor-firebase-analytics',
    author: 'github.com/Cap-go',
    description: 'Capacitor plugin for Firebase Analytics',
    href: 'https://github.com/Cap-go/capacitor-firebase/tree/main/packages/analytics',
    title: 'Firebase Analytics',
    icon: 'ChartBar',
  },
  {
    name: '@capgo/capacitor-firebase-app',
    author: 'github.com/Cap-go',
    description: 'Capacitor plugin for Firebase App',
    href: 'https://github.com/Cap-go/capacitor-firebase/tree/main/packages/app',
    title: 'Firebase App',
    icon: 'Fire',
  },
  {
    name: '@capgo/capacitor-firebase-app-check',
    author: 'github.com/Cap-go',
    description: 'Capacitor plugin for Firebase App Check',
    href: 'https://github.com/Cap-go/capacitor-firebase/tree/main/packages/app-check',
    title: 'Firebase App Check',
    icon: 'ShieldCheck',
  },
  {
    name: '@capgo/capacitor-firebase-authentication',
    author: 'github.com/Cap-go',
    description: 'Capacitor plugin for Firebase Authentication',
    href: 'https://github.com/Cap-go/capacitor-firebase/tree/main/packages/authentication',
    title: 'Firebase Authentication',
    icon: 'UserCircle',
  },
  {
    name: '@capgo/capacitor-firebase-crashlytics',
    author: 'github.com/Cap-go',
    description: 'Capacitor plugin for Firebase Crashlytics',
    href: 'https://github.com/Cap-go/capacitor-firebase/tree/main/packages/crashlytics',
    title: 'Firebase Crashlytics',
    icon: 'ExclamationTriangle',
  },
  {
    name: '@capgo/capacitor-firebase-firestore',
    author: 'github.com/Cap-go',
    description: 'Capacitor plugin for Firebase Cloud Firestore',
    href: 'https://github.com/Cap-go/capacitor-firebase/tree/main/packages/firestore',
    title: 'Firebase Firestore',
    icon: 'CircleStack',
  },
  {
    name: '@capgo/capacitor-firebase-functions',
    author: 'github.com/Cap-go',
    description: 'Capacitor plugin for Firebase Cloud Functions',
    href: 'https://github.com/Cap-go/capacitor-firebase/tree/main/packages/functions',
    title: 'Firebase Functions',
    icon: 'CommandLine',
  },
  {
    name: '@capgo/capacitor-firebase-messaging',
    author: 'github.com/Cap-go',
    description: 'Capacitor plugin for Firebase Cloud Messaging (FCM)',
    href: 'https://github.com/Cap-go/capacitor-firebase/tree/main/packages/messaging',
    title: 'Firebase Messaging',
    icon: 'ChatBubbleLeft',
  },
  {
    name: '@capgo/capacitor-firebase-performance',
    author: 'github.com/Cap-go',
    description: 'Capacitor plugin for Firebase Performance Monitoring',
    href: 'https://github.com/Cap-go/capacitor-firebase/tree/main/packages/performance',
    title: 'Firebase Performance',
    icon: 'RocketLaunch',
  },
  {
    name: '@capgo/capacitor-firebase-remote-config',
    author: 'github.com/Cap-go',
    description: 'Capacitor plugin for Firebase Remote Config',
    href: 'https://github.com/Cap-go/capacitor-firebase/tree/main/packages/remote-config',
    title: 'Firebase Remote Config',
    icon: 'Cog',
  },
  {
    name: '@capgo/capacitor-firebase-storage',
    author: 'github.com/Cap-go',
    description: 'Capacitor plugin for Firebase Cloud Storage',
    href: 'https://github.com/Cap-go/capacitor-firebase/tree/main/packages/storage',
    title: 'Firebase Storage',
    icon: 'Cloud',
  },
  {
    name: '@capacitor-plus/core',
    author: 'github.com/Cap-go',
    description: 'Capacitor+ is an automated, always-synced fork of Capacitor with merged community PRs and rapid releases',
    href: 'https://github.com/Cap-go/capacitor-plus/',
    title: 'Capacitor+ Core',
    icon: 'ArrowsRightLeft',
  },
  {
    name: '@capacitor-plus/cli',
    author: 'github.com/Cap-go',
    description: 'Capacitor+ CLI - Same as official CLI but with community improvements merged faster',
    href: 'https://github.com/Cap-go/capacitor-plus/',
    title: 'Capacitor+ CLI',
    icon: 'CommandLine',
  },
  {
    name: '@capacitor-plus/android',
    author: 'github.com/Cap-go',
    description: 'Capacitor+ Android runtime - Drop-in replacement with merged community fixes',
    href: 'https://github.com/Cap-go/capacitor-plus/',
    title: 'Capacitor+ Android',
    icon: 'DevicePhoneMobile',
  },
  {
    name: '@capacitor-plus/ios',
    author: 'github.com/Cap-go',
    description: 'Capacitor+ iOS runtime - Drop-in replacement with merged community fixes',
    href: 'https://github.com/Cap-go/capacitor-plus/',
    title: 'Capacitor+ iOS',
    icon: 'DevicePhoneMobile',
  },
  {
    name: '@capgo/capacitor-compass',
    author: 'github.com/Cap-go',
    description: 'Read device compass heading in degrees with continuous updates and permission handling',
    href: 'https://github.com/Cap-go/capacitor-compass/',
    title: 'Compass',
    icon: 'MapPin',
  },
  {
    name: '@capgo/capacitor-file',
    author: 'github.com/Cap-go',
    description: 'Full-featured file system plugin for reading, writing, and managing files and directories',
    href: 'https://github.com/Cap-go/capacitor-file/',
    title: 'File',
    icon: 'Folder',
  },
  {
    name: '@capgo/capacitor-bluetooth-low-energy',
    author: 'github.com/Cap-go',
    description: 'Full-featured BLE plugin for scanning, connecting, reading, writing, and receiving notifications from Bluetooth devices',
    href: 'https://github.com/Cap-go/capacitor-bluetooth-low-energy/',
    title: 'Bluetooth Low Energy',
    icon: 'Radio',
  },
  {
    name: '@capgo/capacitor-keep-awake',
    author: 'github.com/Cap-go',
    description: 'Prevent device screen from dimming or sleeping for video players, navigation, and presentations',
    href: 'https://github.com/Cap-go/capacitor-keep-awake/',
    title: 'Keep Awake',
    icon: 'Sun',
  },
  {
    name: '@capgo/capacitor-in-app-review',
    author: 'github.com/Cap-go',
    description: 'Prompt users to submit app store ratings and reviews without leaving your app using native iOS and Android APIs',
    href: 'https://github.com/Cap-go/capacitor-in-app-review/',
    title: 'In App Review',
    icon: 'Star',
  },
  {
    name: '@capgo/capacitor-file-picker',
    author: 'github.com/Cap-go',
    description: 'Pick files, images, videos, and directories with full native support for iOS and Android including HEIC conversion',
    href: 'https://github.com/Cap-go/capacitor-file-picker/',
    title: 'File Picker',
    icon: 'FolderOpen',
  },
  {
    name: '@capgo/capacitor-watch',
    author: 'github.com/Cap-go',
    description: 'Apple Watch communication with bidirectional messaging between iPhone and watchOS apps',
    href: 'https://github.com/Cap-go/capacitor-watch/',
    title: 'Watch',
    icon: 'Clock',
  },
  {
    name: '@capgo/capacitor-brightness',
    author: 'github.com/Cap-go',
    description: 'Control device screen brightness programmatically with support for app-specific and system-wide control',
    href: 'https://github.com/Cap-go/capacitor-brightness/',
    title: 'Brightness',
    icon: 'Sun',
  },
  {
    name: '@capgo/capacitor-light-sensor',
    author: 'github.com/Cap-go',
    description: 'Access the ambient light sensor to measure illuminance levels in lux with real-time updates',
    href: 'https://github.com/Cap-go/capacitor-light-sensor/',
    title: 'Light Sensor',
    icon: 'Eye',
  },
  {
    name: '@capgo/capacitor-video-thumbnails',
    author: 'github.com/Cap-go',
    description: 'Generate thumbnail images from local and remote video files at specific timestamps',
    href: 'https://github.com/Cap-go/capacitor-video-thumbnails/',
    title: 'Video Thumbnails',
    icon: 'Film',
  },
  {
    name: '@capgo/capacitor-intent-launcher',
    author: 'github.com/Cap-go',
    description: 'Launch Android intents, open system settings, and interact with other apps using the Intent system',
    href: 'https://github.com/Cap-go/capacitor-intent-launcher/',
    title: 'Intent Launcher',
    icon: 'RocketLaunch',
  },
]
