export interface SolutionStoreApp {
  appId: string
  title: string
  icon: string
  url: string
  category: string
  installs: number
  score: number
}

type SolutionStoreAppRow = readonly [appId: string, title: string, icon: string, url: string, category: string, installs: number, score: number]

// Sourced from the Cloudflare D1 store_apps table in capgo_prod_storeapp.
const solutionStoreAppRows = [
  [
    'gov.fema.mobile.android',
    'FEMA',
    'https://play-lh.googleusercontent.com/okrUGchhgopCmYQ-wqWQ_fIjP7ZfklGjIYMPMrVHGCi1CRcr6qsztHfADDU0IGqDM',
    'https://play.google.com/store/apps/details?id=gov.fema.mobile.android',
    'WEATHER',
    1649325,
    3.9977221,
  ],
  [
    'au.com.hotdoc.android.hotdoc',
    'HotDoc',
    'https://play-lh.googleusercontent.com/YP3F0StAPaPeVfC2QDtP6qJviIrymUKUHClyQzfSZHsWjW8s6f5djHfaai37iAS6wg',
    'https://play.google.com/store/apps/details?id=au.com.hotdoc.android.hotdoc',
    'MEDICAL',
    2055327,
    4.5784903,
  ],
  [
    'br.com.beneficiario.odontoprev',
    'Odontoprev',
    'https://play-lh.googleusercontent.com/-VO9joxW9BAc1pUY1pnIx_GaFnHmNED4-GxQP1IUCfgVo8YIqJj0cpODKqAWSZp6cg',
    'https://play.google.com/store/apps/details?id=br.com.beneficiario.odontoprev',
    'MEDICAL',
    1871596,
    4.504618,
  ],
  [
    'br.com.oi.tecnicovirtual',
    'Técnico Virtual – Suporte Técn',
    'https://play-lh.googleusercontent.com/Z6dllHB0cJ7mRTder7aN95E9eU-jyuChCVRKQOiVpvuieQjyh3gcswY19J3e_c6t',
    'https://play.google.com/store/apps/details?id=br.com.oi.tecnicovirtual&hl=en&gl=us',
    'Tools',
    10336382,
    4.31,
  ],
  [
    'br.gov.datasus.cnsdigital',
    'Conecte SUS',
    'https://play-lh.googleusercontent.com/_ItDzVkRcYdSviiAzBB4KECwSfbP7ZfklGjIYMPMrVHGCi1CRcr6qsztHfADDU0IGqDM',
    'https://play.google.com/store/apps/details?id=br.gov.datasus.cnsdigital',
    'MEDICAL',
    27678757,
    4.568998,
  ],
  [
    'br.jus.tse.eleitoral.etitulo',
    'e-Título',
    'https://play-lh.googleusercontent.com/2K6urTCerr6loFfG7pNP3wRqM3HVpT4xMyCa4BSGwqqm_olC2hoN8fCFOPDryc9kwE8',
    'https://play.google.com/store/apps/details?id=br.jus.tse.eleitoral.etitulo',
    'SOCIAL',
    54855118,
    4.754247,
  ],
  [
    'br.jus.tse.resultados',
    'Resultados',
    'https://play-lh.googleusercontent.com/rKvQQroGJA86vCG0eDqVeFZsltKxMlQWvmH-nFN-tRBYANShKEQKEPeK7G7NrTyX4g',
    'https://play.google.com/store/apps/details?id=br.jus.tse.resultados&hl=en&gl=us',
    'Tools',
    14975218,
    2.76,
  ],
  [
    'com.IndianBank.IndOASIS',
    'IndOASIS Indian Bank MobileApp',
    'https://play-lh.googleusercontent.com/LGtygldnmgC4ji-3ZqfU78iXolZbVw1fjHOxKlmsOui2ZjltZg4TkHzEkO2-yCnSprZf',
    'https://play.google.com/store/apps/details?id=com.IndianBank.IndOASIS',
    'FINANCE',
    15436092,
    4.2306004,
  ],
  [
    'com.dennys.mobile',
    "Denny's",
    'https://play-lh.googleusercontent.com/x7yKSH2i3m3mqiBwd2hVrojVq2c-GpiKIFbo2Q3PFdvgj_Z4i6Cb26lUhLVbEf5BIaeu',
    'https://play.google.com/store/apps/details?id=com.dennys.mobile',
    'FOOD_AND_DRINK',
    1727335,
    4.6823587,
  ],
  [
    'com.freelancer.android.messenger',
    'Freelancer: Hire & Find Jobs',
    'https://play-lh.googleusercontent.com/DK7BGyOA_2Z_oYvoPRdC4f8JnURBCE1pDKPyEXd0B190U2p57Fr9LifujFegPAG6MA',
    'https://play.google.com/store/apps/details?id=com.freelancer.android.messenger',
    'BUSINESS',
    8941852,
    4.086302,
  ],
  [
    'com.greetingsisland.sam',
    'Invitation Maker Card Design',
    'https://play-lh.googleusercontent.com/9dU02jjAkV7HXxK5AOYMqkJEsZ4In8YWBI2F6XH8l4BnT-vNxUwI16Ms3FfeEcs6Up4',
    'https://play.google.com/store/apps/details?id=com.greetingsisland.sam',
    'EVENTS',
    19967814,
    4.5748262,
  ],
  [
    'com.infrasoft.uboi',
    'Vyom - Union Bank of India',
    'https://play-lh.googleusercontent.com/mlL6e-9TQL_vIcOt79KCDzArLc_hyWJYKDGKKP2bwGe0q3EJS0HRFJuz41d2n-Xvng',
    'https://play.google.com/store/apps/details?id=com.infrasoft.uboi',
    'FINANCE',
    27979178,
    3.6850767,
  ],
  [
    'com.jackintheboxinc.JackMobileApp',
    'Jack in the Box® - Order Food',
    'https://play-lh.googleusercontent.com/0nYXXrfykZoepAyeF-SUmh8NXCiIptd8bPKZlKueJ0RBA6HXtSRCPmA4hcwADvwmVrc',
    'https://play.google.com/store/apps/details?id=com.jackintheboxinc.JackMobileApp',
    'Food & Drink',
    2702012,
    2.5235932,
  ],
  [
    'com.jernung.infinite.jpn',
    'Infinite Japanese',
    'https://play-lh.googleusercontent.com/19818WQw8abVv7uXuJZyA6cGyM7HP17Zh-_2PqDT5-9w8DEeJbOg-7Ip1X70rf7AbrT_',
    'https://play.google.com/store/apps/details?id=com.jernung.infinite.jpn&hl=en&gl=us',
    'Educational',
    1804981,
    4.64396,
  ],
  [
    'com.kai.kaiticketing',
    'KAI Access: Train Booking App',
    'https://play-lh.googleusercontent.com/dnFOQqguRQB6G0BVca-YNaPGYDfgTOK3BGvlyOr4s6w-6-U17V2iYnLKmgau865mWOs',
    'https://play.google.com/store/apps/details?id=com.kai.kaiticketing',
    'TRAVEL_AND_LOCAL',
    13496796,
    3.5697675,
  ],
  [
    'com.morrisons.matchandmore.app',
    'My Morrisons',
    'https://play-lh.googleusercontent.com/9IKXGc-hU9LvQn7Bhvv6b5kUe6PsPmsnBs9TpDtFZfK_scJ-7QkR8oE8RDgP5FGeHnY',
    'https://play.google.com/store/apps/details?id=com.morrisons.matchandmore.app',
    'SHOPPING',
    2824658,
    3.1080246,
  ],
  [
    'com.mushroomcloud.cars',
    'Cars.co.za',
    'https://play-lh.googleusercontent.com/WUYcnzz9FG4MTxg98F98km6LYVK3_EhJsQP_hs8m4K902F39iDuomosyhRGIQPxj0_3b',
    'https://play.google.com/store/apps/details?id=com.mushroomcloud.cars',
    'AUTO_AND_VEHICLES',
    1886114,
    4.375,
  ],
  [
    'com.orange.miorange',
    'Mi Orange',
    'https://play-lh.googleusercontent.com/NXY743Tphk0kApA9B34LMcOxBotwPrxawdbANUHGTyj2kUVVxmXNm2eX4FDDcaWB6-E',
    'https://play.google.com/store/apps/details?id=com.orange.miorange',
    'TOOLS',
    9336196,
    4.2226048,
  ],
  [
    'com.orange.mobile.orangemoney',
    'Orange Money Sénégal',
    'https://play-lh.googleusercontent.com/T4ZLP7nx1kM6oXacVqAlCqQ5d11xc1NPdC9i3iofouWGIuXXo9QW0FsQJGA01AEblDRo',
    'https://play.google.com/store/apps/details?id=com.orange.mobile.orangemoney',
    'FINANCE',
    2574366,
    4.0321665,
  ],
  [
    'com.paylocity.paylocitymobile',
    'Paylocity Mobile',
    'https://play-lh.googleusercontent.com/oTtp5ay3Ht12U7sSv1ixCaXgqIjyiYLUgo4eoze4d9mxgpCgMl76-uc4ouoVrIPR9G0',
    'https://play.google.com/store/apps/details?id=com.paylocity.paylocitymobile',
    'BUSINESS',
    3132112,
    3.5820224,
  ],
  [
    'de.tvspielfilm',
    'TV SPIELFILM - TV-Programm',
    'https://play-lh.googleusercontent.com/leo6t9uMZUdgwmQNZnk1gqjwV04reFKWmoAjuimPK9k5_Zbzoky_7mrNrfXsULognS8',
    'https://play.google.com/store/apps/details?id=de.tvspielfilm',
    'ENTERTAINMENT',
    12126454,
    4.389995,
  ],
  [
    'com.polleverywhere.mobile',
    'Poll Everywhere',
    'https://play-lh.googleusercontent.com/gVe6IqmsUdPZPI0jS6dSSmEgBNIpAgBbwJlx51lSe_isN8yjNoiXMvxJtqdc64H0RQ',
    'https://play.google.com/store/apps/details?id=com.polleverywhere.mobile',
    'BUSINESS',
    1135271,
    3.2272727,
  ],
  [
    'com.studysmarter',
    'StudySmarter - School & uni',
    'https://play-lh.googleusercontent.com/j2qPOVSwqKIdUCZJjFN4yF-GulBon9moWrM3qUFDFgZCQ6Fjzv97a26OASWmL5JfYw',
    'https://play.google.com/store/apps/details?id=com.studysmarter',
    'EDUCATION',
    6480843,
    4.76,
  ],
  [
    'com.swisscom.myswisscom',
    'My Swisscom',
    'https://play-lh.googleusercontent.com/a_ElP-zHCheGbkYICNzsqOXqdGAKLbJ-eEq6ukQWj3xfhwc7EjOSI0_WQAi_9zUI_5sl',
    'https://play.google.com/store/apps/details?id=com.swisscom.myswisscom',
    'PRODUCTIVITY',
    1758453,
    4.374247,
  ],
  [
    'com.wegmans.wegmansapp',
    'Wegmans',
    'https://play-lh.googleusercontent.com/FffojmhAqdpRPWU-DoJDNk0D2zlhCOEVPFm2fQ-RIFxlML1yIIH0UXwEpjsoSNA1kY_e',
    'https://play.google.com/store/apps/details?id=com.wegmans.wegmansapp',
    'SHOPPING',
    1286319,
    3.6846848,
  ],
  [
    'com.windyty.android',
    'Windy.com - Weather Forecast',
    'https://play-lh.googleusercontent.com/qXBOdC6WVNPPZso8m5_Z_lCiNTG130ZwHAumXlLpF5r9yaPYICJw9tGGtPt5v9yh35E',
    'https://play.google.com/store/apps/details?id=com.windyty.android',
    'WEATHER',
    32919408,
    4.6538405,
  ],
  [
    'de.burgerking.kingfinder',
    'BURGER KING®',
    'https://play-lh.googleusercontent.com/PDSuJ9JjikJ2kNqMoKFEOJ6NpX7_SNXJuW7ixBRiqR_ptEBjjYn5JFm3W4DO7zHMQ5M',
    'https://play.google.com/store/apps/details?id=de.burgerking.kingfinder',
    'APPLICATION',
    14264075,
    3.9216425,
  ],
  [
    'gt.com.tigosports',
    'Tigo Sports Guatemala',
    'https://play-lh.googleusercontent.com/KH-g_YGtjU5GdfVyNZlvi40ld8mN0Nf5KQuRxRvGd_McffdR7wA95zLDn7eV0khH_0o',
    'https://play.google.com/store/apps/details?id=gt.com.tigosports',
    'SPORTS',
    1569649,
    3.2618597,
  ],
  [
    'net.bitburst.pollpay',
    'Poll Pay: Money for Surveys',
    'https://play-lh.googleusercontent.com/0ChVi4ei7TtNUdAase4IK61Gbm010dCM5AlQVMobw32ZLG_bZyF-u3ToYU032N9XDXQ',
    'https://play.google.com/store/apps/details?id=net.bitburst.pollpay',
    'LIFESTYLE',
    11295030,
    4.4488664,
  ],
  [
    'net.groceryshopping.SproutsFarmersMarket',
    'Sprouts',
    'https://play-lh.googleusercontent.com/08bY9GrB1UtfY8T6DGbJgea8NaDkF-XMOFvjLfjqYF-KhJphiNlwznohXyKhvfljdkk',
    'https://play.google.com/store/apps/details?id=net.groceryshopping.SproutsFarmersMarket',
    'SHOPPING',
    1350282,
    4.2526884,
  ],
  [
    'org.lichess.mobileapp',
    'lichess • Free Online Chess',
    'https://play-lh.googleusercontent.com/5bZvh2nmZ-2B-kcKTuATofj5bhscTrJqveAHGYVoJKalfFOMEgx2VnyOth7oJ8bJzQ',
    'https://play.google.com/store/apps/details?id=org.lichess.mobileapp',
    'GAME_BOARD',
    11343228,
    4.3332243,
  ],
  [
    'ua.vodafone.myvodafone',
    'My Vodafone',
    'https://play-lh.googleusercontent.com/xuGh4YAt0sOfSJJbfd3unyYKWvcgVZ1xxy62UwICVxct9f53kvT0-xnwVvIpOMSRrgg',
    'https://play.google.com/store/apps/details?id=ua.vodafone.myvodafone',
    'TOOLS',
    11056716,
    4.6200433,
  ],
  [
    'uk.co.parentmail.parentmail',
    'IRIS ParentMail',
    'https://play-lh.googleusercontent.com/f_kS--49imp8pRbkLC6rQAZ2kiFCr2s39kyn0L_d_boV23sKRTQI8JVQAhPe_smk2jQ',
    'https://play.google.com/store/apps/details?id=uk.co.parentmail.parentmail',
    'Education',
    1245646,
    2.8313253,
  ],
] as const satisfies readonly SolutionStoreAppRow[]

export type SolutionStoreAppId = (typeof solutionStoreAppRows)[number][0]

export const solutionStoreApps = Object.fromEntries(
  solutionStoreAppRows.map(([appId, title, icon, url, category, installs, score]) => [appId, { appId, title, icon, url, category, installs, score }]),
) as Record<SolutionStoreAppId, SolutionStoreApp>
