export interface SolutionStoreApp {
  appId: string
  title: string
  icon: string
  url: string
  category: string
  installs: number
  score: number
}

// Sourced from the Cloudflare D1 store_apps table in capgo_prod_storeapp.
export const solutionStoreApps = {
  'air.com.playtika.slotomania': {
    appId: 'air.com.playtika.slotomania',
    title: 'Slotomania™ Slots Casino Games',
    icon: 'https://play-lh.googleusercontent.com/zGFaKYbx3cum12bnLD4E9GTl8ZU3uL_VVkavfiJqYCPx3F7GYHwripUx3lavhytq89M',
    url: 'https://play.google.com/store/apps/details?id=air.com.playtika.slotomania',
    category: 'GAME',
    installs: 79313129,
    score: 4.4084463,
  },
  'au.com.hotdoc.android.hotdoc': {
    appId: 'au.com.hotdoc.android.hotdoc',
    title: 'HotDoc',
    icon: 'https://play-lh.googleusercontent.com/YP3F0StAPaPeVfC2QDtP6qJviIrymUKUHClyQzfSZHsWjW8s6f5djHfaai37iAS6wg',
    url: 'https://play.google.com/store/apps/details?id=au.com.hotdoc.android.hotdoc',
    category: 'MEDICAL',
    installs: 2055327,
    score: 4.5784903,
  },
  'br.com.beneficiario.odontoprev': {
    appId: 'br.com.beneficiario.odontoprev',
    title: 'Odontoprev',
    icon: 'https://play-lh.googleusercontent.com/-VO9joxW9BAc1pUY1pnIx_GaFnHmNED4-GxQP1IUCfgVo8YIqJj0cpODKqAWSZp6cg',
    url: 'https://play.google.com/store/apps/details?id=br.com.beneficiario.odontoprev',
    category: 'MEDICAL',
    installs: 1871596,
    score: 4.504618,
  },
  'br.com.oi.tecnicovirtual': {
    appId: 'br.com.oi.tecnicovirtual',
    title: 'Técnico Virtual – Suporte Técn',
    icon: 'https://play-lh.googleusercontent.com/Z6dllHB0cJ7mRTder7aN95E9eU-jyuChCVRKQOiVpvuieQjyh3gcswY19J3e_c6t',
    url: 'https://play.google.com/store/apps/details?id=br.com.oi.tecnicovirtual&hl=en&gl=us',
    category: 'Tools',
    installs: 10336382,
    score: 4.31,
  },
  'br.gov.datasus.cnsdigital': {
    appId: 'br.gov.datasus.cnsdigital',
    title: 'Conecte SUS',
    icon: 'https://play-lh.googleusercontent.com/_ItDzVkRcYdSviiAzBB4KECwSfbP7ZfklGjIYMPMrVHGCi1CRcr6qsztHfADDU0IGqDM',
    url: 'https://play.google.com/store/apps/details?id=br.gov.datasus.cnsdigital',
    category: 'MEDICAL',
    installs: 27678757,
    score: 4.568998,
  },
  'br.jus.tse.eleitoral.etitulo': {
    appId: 'br.jus.tse.eleitoral.etitulo',
    title: 'e-Título',
    icon: 'https://play-lh.googleusercontent.com/2K6urTCerr6loFfG7pNP3wRqM3HVpT4xMyCa4BSGwqqm_olC2hoN8fCFOPDryc9kwE8',
    url: 'https://play.google.com/store/apps/details?id=br.jus.tse.eleitoral.etitulo',
    category: 'SOCIAL',
    installs: 54855118,
    score: 4.754247,
  },
  'br.jus.tse.resultados': {
    appId: 'br.jus.tse.resultados',
    title: 'Resultados',
    icon: 'https://play-lh.googleusercontent.com/rKvQQroGJA86vCG0eDqVeFZsltKxMlQWvmH-nFN-tRBYANShKEQKEPeK7G7NrTyX4g',
    url: 'https://play.google.com/store/apps/details?id=br.jus.tse.resultados&hl=en&gl=us',
    category: 'Tools',
    installs: 14975218,
    score: 2.76,
  },
  'com.IndianBank.IndOASIS': {
    appId: 'com.IndianBank.IndOASIS',
    title: 'IndOASIS Indian Bank MobileApp',
    icon: 'https://play-lh.googleusercontent.com/LGtygldnmgC4ji-3ZqfU78iXolZbVw1fjHOxKlmsOui2ZjltZg4TkHzEkO2-yCnSprZf',
    url: 'https://play.google.com/store/apps/details?id=com.IndianBank.IndOASIS',
    category: 'FINANCE',
    installs: 15436092,
    score: 4.2306004,
  },
  'com.dennys.mobile': {
    appId: 'com.dennys.mobile',
    title: "Denny's",
    icon: 'https://play-lh.googleusercontent.com/x7yKSH2i3m3mqiBwd2hVrojVq2c-GpiKIFbo2Q3PFdvgj_Z4i6Cb26lUhLVbEf5BIaeu',
    url: 'https://play.google.com/store/apps/details?id=com.dennys.mobile',
    category: 'FOOD_AND_DRINK',
    installs: 1727335,
    score: 4.6823587,
  },
  'com.freelancer.android.messenger': {
    appId: 'com.freelancer.android.messenger',
    title: 'Freelancer: Hire & Find Jobs',
    icon: 'https://play-lh.googleusercontent.com/DK7BGyOA_2Z_oYvoPRdC4f8JnURBCE1pDKPyEXd0B190U2p57Fr9LifujFegPAG6MA',
    url: 'https://play.google.com/store/apps/details?id=com.freelancer.android.messenger',
    category: 'BUSINESS',
    installs: 8941852,
    score: 4.086302,
  },
  'com.greetingsisland.sam': {
    appId: 'com.greetingsisland.sam',
    title: 'Invitation Maker Card Design',
    icon: 'https://play-lh.googleusercontent.com/9dU02jjAkV7HXxK5AOYMqkJEsZ4In8YWBI2F6XH8l4BnT-vNxUwI16Ms3FfeEcs6Up4',
    url: 'https://play.google.com/store/apps/details?id=com.greetingsisland.sam',
    category: 'EVENTS',
    installs: 19967814,
    score: 4.5748262,
  },
  'com.infrasoft.uboi': {
    appId: 'com.infrasoft.uboi',
    title: 'Vyom - Union Bank of India',
    icon: 'https://play-lh.googleusercontent.com/mlL6e-9TQL_vIcOt79KCDzArLc_hyWJYKDGKKP2bwGe0q3EJS0HRFJuz41d2n-Xvng',
    url: 'https://play.google.com/store/apps/details?id=com.infrasoft.uboi',
    category: 'FINANCE',
    installs: 27979178,
    score: 3.6850767,
  },
  'com.jackintheboxinc.JackMobileApp': {
    appId: 'com.jackintheboxinc.JackMobileApp',
    title: 'Jack in the Box® - Order Food',
    icon: 'https://play-lh.googleusercontent.com/0nYXXrfykZoepAyeF-SUmh8NXCiIptd8bPKZlKueJ0RBA6HXtSRCPmA4hcwADvwmVrc',
    url: 'https://play.google.com/store/apps/details?id=com.jackintheboxinc.JackMobileApp',
    category: 'Food & Drink',
    installs: 2702012,
    score: 2.5235932,
  },
  'com.jernung.infinite.jpn': {
    appId: 'com.jernung.infinite.jpn',
    title: 'Infinite Japanese',
    icon: 'https://play-lh.googleusercontent.com/19818WQw8abVv7uXuJZyA6cGyM7HP17Zh-_2PqDT5-9w8DEeJbOg-7Ip1X70rf7AbrT_',
    url: 'https://play.google.com/store/apps/details?id=com.jernung.infinite.jpn&hl=en&gl=us',
    category: 'Educational',
    installs: 1804981,
    score: 4.64396,
  },
  'com.kai.kaiticketing': {
    appId: 'com.kai.kaiticketing',
    title: 'KAI Access: Train Booking App',
    icon: 'https://play-lh.googleusercontent.com/dnFOQqguRQB6G0BVca-YNaPGYDfgTOK3BGvlyOr4s6w-6-U17V2iYnLKmgau865mWOs',
    url: 'https://play.google.com/store/apps/details?id=com.kai.kaiticketing',
    category: 'TRAVEL_AND_LOCAL',
    installs: 13496796,
    score: 3.5697675,
  },
  'com.morrisons.matchandmore.app': {
    appId: 'com.morrisons.matchandmore.app',
    title: 'My Morrisons',
    icon: 'https://play-lh.googleusercontent.com/9IKXGc-hU9LvQn7Bhvv6b5kUe6PsPmsnBs9TpDtFZfK_scJ-7QkR8oE8RDgP5FGeHnY',
    url: 'https://play.google.com/store/apps/details?id=com.morrisons.matchandmore.app',
    category: 'SHOPPING',
    installs: 2824658,
    score: 3.1080246,
  },
  'com.mushroomcloud.cars': {
    appId: 'com.mushroomcloud.cars',
    title: 'Cars.co.za',
    icon: 'https://play-lh.googleusercontent.com/WUYcnzz9FG4MTxg98F98km6LYVK3_EhJsQP_hs8m4K902F39iDuomosyhRGIQPxj0_3b',
    url: 'https://play.google.com/store/apps/details?id=com.mushroomcloud.cars',
    category: 'AUTO_AND_VEHICLES',
    installs: 1886114,
    score: 4.375,
  },
  'com.orange.miorange': {
    appId: 'com.orange.miorange',
    title: 'Mi Orange',
    icon: 'https://play-lh.googleusercontent.com/NXY743Tphk0kApA9B34LMcOxBotwPrxawdbANUHGTyj2kUVVxmXNm2eX4FDDcaWB6-E',
    url: 'https://play.google.com/store/apps/details?id=com.orange.miorange',
    category: 'TOOLS',
    installs: 9336196,
    score: 4.2226048,
  },
  'com.orange.mobile.orangemoney': {
    appId: 'com.orange.mobile.orangemoney',
    title: 'Orange Money Sénégal',
    icon: 'https://play-lh.googleusercontent.com/T4ZLP7nx1kM6oXacVqAlCqQ5d11xc1NPdC9i3iofouWGIuXXo9QW0FsQJGA01AEblDRo',
    url: 'https://play.google.com/store/apps/details?id=com.orange.mobile.orangemoney',
    category: 'FINANCE',
    installs: 2574366,
    score: 4.0321665,
  },
  'com.paylocity.paylocitymobile': {
    appId: 'com.paylocity.paylocitymobile',
    title: 'Paylocity Mobile',
    icon: 'https://play-lh.googleusercontent.com/oTtp5ay3Ht12U7sSv1ixCaXgqIjyiYLUgo4eoze4d9mxgpCgMl76-uc4ouoVrIPR9G0',
    url: 'https://play.google.com/store/apps/details?id=com.paylocity.paylocitymobile',
    category: 'BUSINESS',
    installs: 3132112,
    score: 3.5820224,
  },
  'com.playtika.caesarscasino': {
    appId: 'com.playtika.caesarscasino',
    title: 'Caesars Slots: Casino Games',
    icon: 'https://play-lh.googleusercontent.com/qGzmTgAvvvF5NaFqHB8Y7rejLkffI3zHWFEYJzcXMlXi2yBQBTvvRd69ZRn9ma8LJmw',
    url: 'https://play.google.com/store/apps/details?id=com.playtika.caesarscasino',
    category: 'GAME_CASINO',
    installs: 31896616,
    score: 4.463003,
  },
  'com.polleverywhere.mobile': {
    appId: 'com.polleverywhere.mobile',
    title: 'Poll Everywhere',
    icon: 'https://play-lh.googleusercontent.com/gVe6IqmsUdPZPI0jS6dSSmEgBNIpAgBbwJlx51lSe_isN8yjNoiXMvxJtqdc64H0RQ',
    url: 'https://play.google.com/store/apps/details?id=com.polleverywhere.mobile',
    category: 'BUSINESS',
    installs: 1135271,
    score: 3.2272727,
  },
  'com.studysmarter': {
    appId: 'com.studysmarter',
    title: 'StudySmarter - School & uni',
    icon: 'https://play-lh.googleusercontent.com/j2qPOVSwqKIdUCZJjFN4yF-GulBon9moWrM3qUFDFgZCQ6Fjzv97a26OASWmL5JfYw',
    url: 'https://play.google.com/store/apps/details?id=com.studysmarter',
    category: 'EDUCATION',
    installs: 6480843,
    score: 4.76,
  },
  'com.swisscom.myswisscom': {
    appId: 'com.swisscom.myswisscom',
    title: 'My Swisscom',
    icon: 'https://play-lh.googleusercontent.com/a_ElP-zHCheGbkYICNzsqOXqdGAKLbJ-eEq6ukQWj3xfhwc7EjOSI0_WQAi_9zUI_5sl',
    url: 'https://play.google.com/store/apps/details?id=com.swisscom.myswisscom',
    category: 'PRODUCTIVITY',
    installs: 1758453,
    score: 4.374247,
  },
  'com.wegmans.wegmansapp': {
    appId: 'com.wegmans.wegmansapp',
    title: 'Wegmans',
    icon: 'https://play-lh.googleusercontent.com/FffojmhAqdpRPWU-DoJDNk0D2zlhCOEVPFm2fQ-RIFxlML1yIIH0UXwEpjsoSNA1kY_e',
    url: 'https://play.google.com/store/apps/details?id=com.wegmans.wegmansapp',
    category: 'SHOPPING',
    installs: 1286319,
    score: 3.6846848,
  },
  'com.windyty.android': {
    appId: 'com.windyty.android',
    title: 'Windy.com - Weather Forecast',
    icon: 'https://play-lh.googleusercontent.com/qXBOdC6WVNPPZso8m5_Z_lCiNTG130ZwHAumXlLpF5r9yaPYICJw9tGGtPt5v9yh35E',
    url: 'https://play.google.com/store/apps/details?id=com.windyty.android',
    category: 'WEATHER',
    installs: 32919408,
    score: 4.6538405,
  },
  'de.burgerking.kingfinder': {
    appId: 'de.burgerking.kingfinder',
    title: 'BURGER KING®',
    icon: 'https://play-lh.googleusercontent.com/PDSuJ9JjikJ2kNqMoKFEOJ6NpX7_SNXJuW7ixBRiqR_ptEBjjYn5JFm3W4DO7zHMQ5M',
    url: 'https://play.google.com/store/apps/details?id=de.burgerking.kingfinder',
    category: 'APPLICATION',
    installs: 14264075,
    score: 3.9216425,
  },
  'de.tvspielfilm': {
    appId: 'de.tvspielfilm',
    title: 'TV SPIELFILM - TV-Programm',
    icon: 'https://play-lh.googleusercontent.com/leo6t9uMZUdgwmQNZnk1gqjwV04reFKWmoAjuimPK9k5_Zbzoky_7mrNrfXsULognS8',
    url: 'https://play.google.com/store/apps/details?id=de.tvspielfilm',
    category: 'ENTERTAINMENT',
    installs: 12126454,
    score: 4.389995,
  },
  'gov.fema.mobile.android': {
    appId: 'gov.fema.mobile.android',
    title: 'FEMA',
    icon: 'https://play-lh.googleusercontent.com/okrUGchhgopCmYQ-wqWQ_fIjP7ZfklGjIYMPMrVHGCi1CRcr6qsztHfADDU0IGqDM',
    url: 'https://play.google.com/store/apps/details?id=gov.fema.mobile.android',
    category: 'WEATHER',
    installs: 1649325,
    score: 3.9977221,
  },
  'gt.com.tigosports': {
    appId: 'gt.com.tigosports',
    title: 'Tigo Sports Guatemala',
    icon: 'https://play-lh.googleusercontent.com/KH-g_YGtjU5GdfVyNZlvi40ld8mN0Nf5KQuRxRvGd_McffdR7wA95zLDn7eV0khH_0o',
    url: 'https://play.google.com/store/apps/details?id=gt.com.tigosports',
    category: 'SPORTS',
    installs: 1569649,
    score: 3.2618597,
  },
  'net.bitburst.pollpay': {
    appId: 'net.bitburst.pollpay',
    title: 'Poll Pay: Money for Surveys',
    icon: 'https://play-lh.googleusercontent.com/0ChVi4ei7TtNUdAase4IK61Gbm010dCM5AlQVMobw32ZLG_bZyF-u3ToYU032N9XDXQ',
    url: 'https://play.google.com/store/apps/details?id=net.bitburst.pollpay',
    category: 'LIFESTYLE',
    installs: 11295030,
    score: 4.4488664,
  },
  'net.groceryshopping.SproutsFarmersMarket': {
    appId: 'net.groceryshopping.SproutsFarmersMarket',
    title: 'Sprouts',
    icon: 'https://play-lh.googleusercontent.com/08bY9GrB1UtfY8T6DGbJgea8NaDkF-XMOFvjLfjqYF-KhJphiNlwznohXyKhvfljdkk',
    url: 'https://play.google.com/store/apps/details?id=net.groceryshopping.SproutsFarmersMarket',
    category: 'SHOPPING',
    installs: 1350282,
    score: 4.2526884,
  },
  'org.lichess.mobileapp': {
    appId: 'org.lichess.mobileapp',
    title: 'lichess • Free Online Chess',
    icon: 'https://play-lh.googleusercontent.com/5bZvh2nmZ-2B-kcKTuATofj5bhscTrJqveAHGYVoJKalfFOMEgx2VnyOth7oJ8bJzQ',
    url: 'https://play.google.com/store/apps/details?id=org.lichess.mobileapp',
    category: 'GAME_BOARD',
    installs: 11343228,
    score: 4.3332243,
  },
  'ua.vodafone.myvodafone': {
    appId: 'ua.vodafone.myvodafone',
    title: 'My Vodafone',
    icon: 'https://play-lh.googleusercontent.com/xuGh4YAt0sOfSJJbfd3unyYKWvcgVZ1xxy62UwICVxct9f53kvT0-xnwVvIpOMSRrgg',
    url: 'https://play.google.com/store/apps/details?id=ua.vodafone.myvodafone',
    category: 'TOOLS',
    installs: 11056716,
    score: 4.6200433,
  },
  'uk.co.parentmail.parentmail': {
    appId: 'uk.co.parentmail.parentmail',
    title: 'IRIS ParentMail',
    icon: 'https://play-lh.googleusercontent.com/f_kS--49imp8pRbkLC6rQAZ2kiFCr2s39kyn0L_d_boV23sKRTQI8JVQAhPe_smk2jQ',
    url: 'https://play.google.com/store/apps/details?id=uk.co.parentmail.parentmail',
    category: 'Education',
    installs: 1245646,
    score: 2.8313253,
  },
} as const satisfies Record<string, SolutionStoreApp>

export type SolutionStoreAppId = keyof typeof solutionStoreApps
