export const actions = [
  {
    name: '@capgo/cli',
    author: 'github.com/riderx',
    description: 'A CLI to upload to capgo servers',
    href: 'https://github.com/Cap-go/capgo-cli/',
    title: 'CLI',
    // icon: CommandLineIcon,
  },
  {
    name: '@capgo/standard-version',
    author: 'Martin Donadieu',
    description: 'replacement for `npm version` with automatic CHANGELOG generation',
    href: 'https://github.com/Cap-go/standard-version/',
    title: 'Standard Version',
    // icon: AdjustmentsHorizontalIcon,
  },
  {
    name: '@capgo/native-market',
    author: 'Martin Donadieu',
    description: 'A native market plugin for linking to google play or app store.',
    href: 'https://github.com/riderx/capacitor-native-market/',
    title: 'Native Market',
    // icon: ArchiveBoxArrowDownIcon,
  },
  {
    name: '@capgo/capacitor-native-biometric',
    author: 'Jose Martinez',
    description: 'This plugin gives access to the native biometric apis for android and iOS',
    href: 'https://github.com/Cap-go/capacitor-native-biometric/',
    title: 'Native Biometric',
    // icon: FingerPrintIcon,
  },
  {
    name: '@capgo/camera-preview',
    author: 'Martin Donadieu',
    description: 'Camera preview',
    href: 'https://github.com/Cap-go/capacitor-camera-preview/',
    title: 'Camera Preview',
    // icon: CameraIcon,
  },
  {
    name: '@capgo/google-play-scraper',
    author: 'Facundo Olano',
    description: 'scrapes app data from google play store',
    href: 'https://github.com/facundoolano/google-play-scraper/',
    title: 'Google Play Scraper',
    // icon: PlayIcon,
  },
  {
    name: '@capgo/ngx-intl-tel-input-app',
    author: 'Unknown',
    description: '[![All Contributors](https://img.shields.io/badge/all_contributors-4-orange.svg?style=flat-square)](#contributors)',
    href: 'N/A',
    title: 'International Telephone Input',
    // icon: PhoneIcon,
  },
  {
    name: '@capgo/konsta',
    author: 'Vladimir Kharlampidi',
    description: 'Mobile UI components made with Tailwind CSS',
    href: 'https://github.com/konstaui/konsta/',
    title: 'Konsta',
    // icon: PaintBrushIcon,
  },
  {
    name: '@capgo/capacitor-updater',
    author: 'Martin Donadieu',
    description: 'Live update for capacitor apps',
    href: 'https://github.com/Cap-go/capacitor-updater/',
    title: 'Updater',
    // icon: ArrowPathIcon,
  },
  {
    name: '@capgo/capacitor-purchases',
    author: 'Martin Donadieu',
    description: 'In-app Subscriptions Made Easy with RevenueCat sdk',
    href: 'https://github.com/Cap-go/capacitor-purchases/',
    title: 'Purchases',
    // icon: CurrencyDollarIcon,
  },
  {
    name: '@capgo/capacitor-flash',
    author: 'Martin Donadieu',
    description: 'Switch the Flashlight / Torch of your device.',
    href: 'https://github.com/riderx/capacitor-flash/',
    title: 'Flash',
    // icon: BoltIcon,
  },
  {
    name: '@capgo/capacitor-screen-recorder',
    author: 'Martin Donadieu',
    // prettier-ignore
    description: 'Record device\'s screen',
    href: 'https://github.com/riderx/capacitor-screen-recorder/',
    title: 'Screen Recorder',
    // icon: VideoCameraIcon,
  },
  {
    name: '@capgo/capacitor-crisp',
    author: 'Martin Donadieu',
    description: 'Crisp native SDK for capacitor',
    href: 'https://github.com/Cap-go/capacitor-crisp/',
    title: 'Crisp',
    // icon: ChatBubbleLeftIcon,
  },
  {
    name: '@capgo/nativegeocoder',
    author: 'Martin Donadieu',
    description: 'Capacitor plugin for native forward and reverse geocoding',
    href: 'https://github.com/Cap-go/capacitor-nativegeocoder/',
    title: 'Native Geocoder',
    // icon: MapPinIcon,
  },
  {
    name: '@capgo/inappbrowser',
    author: 'Martin Donadieu',
    description: 'Capacitor plugin in app browser',
    href: 'https://github.com/Cap-go/capacitor-inappbrowser/',
    title: 'In App Browser',
    // icon: GlobeAltIcon,
  },
  {
    name: '@capgo/capacitor-mute',
    author: 'Martin donadieu',
    description: 'Detect if the mute switch is enabled/disabled on a device',
    href: 'https://github.com/riderx/capacitor-mute/',
    title: 'Mute',
    // icon: SpeakerXMarkIcon,
  },
  // {
  //   name: '@capgo/angular-ng-stepper',
  //   author: 'Giorgi Merabishvili',
  //   description: 'Angular stepper',
  //   href: 'https://github.com/gmerabishvili/angular-ng-stepper/',
  //   title: 'Stepper',
  //   // icon: EllipsisHorizontalIcon,
  // },
  {
    name: '@capgo/native-audio',
    author: 'Martin Donadieu',
    description: 'A native plugin for native audio engine',
    href: 'https://github.com/Cap-go/capacitor-native-audio/',
    title: 'Native Audio',
    // icon: SpeakerWaveIcon,
  },
  {
    name: '@capgo/capacitor-shake',
    author: 'Martin Donadieu',
    description: 'Detect shake gesture in device',
    href: 'https://github.com/Cap-go/capacitor-shake/',
    title: 'Shake',
    // icon: DevicePhoneMobileIcon,
  },
  {
    name: '@capgo/capacitor-navigation-bar',
    author: 'Martin Donadieu',
    description: 'Set navigation bar color for android lolipop and higher',
    href: 'https://github.com/Cap-go/capacitor-navigation-bar/',
    title: 'Navigation Bar',
    // icon: Bars3Icon,
  },
  {
    name: '@capgo/ivs-player',
    author: 'Martin Donadieu',
    description: 'Ivs player for capacitor app',
    href: 'https://github.com/Cap-go/capacitor-ivs-player/',
    title: 'IVS Player',
    // icon: PlayCircleIcon,
  },
  {
    name: '@capgo/home-indicator',
    author: 'Martin Donadieu',
    description: 'hide and show home button indicator in Capacitor app',
    href: 'https://github.com/Cap-go/capacitor-home-indicator/',
    title: 'Indicator',
    // icon: HomeIcon,
  },
  {
    name: '@capgo/find-package-manager',
    author: 'github.com/riderx',
    description: 'Live update for capacitor apps',
    href: 'https://github.com/Cap-go/find-package-manager/',
    title: 'Package Manager',
    // icon: DocumentMagnifyingGlassIcon,
  },
  {
    name: '@capgo/native-purchases',
    author: 'Martin donadieu',
    description: 'In-app Subscriptions Made Easy',
    href: 'https://github.com/Cap-go/capacitor-native-purchases/',
    title: 'Native Purchases',
    // icon: CurrencyDollarIcon,
  },
  {
    name: '@capgo/capacitor-fingerprint',
    author: 'Martin Donadieu',
    description: 'Capacitor client for Fingerprint PRO. 100% accurate device identification for fraud detection.',
    href: 'https://github.com/Cap-go/capacitor-fingerprint/',
    title: 'Fingerprint',
    // icon: FingerPrintIcon,
  },
  {
    name: '@capgo/capacitor-callkit-voip',
    author: 'Martin Donadieu',
    description: 'Provide PushKit functionality to ionic capacitor',
    href: 'https://github.com/Cap-go/capacitor-callkit-voip/',
    title: 'CallKit VOIP',
    // icon: PhoneArrowUpRightIcon,
  },
  {
    name: '@capgo/logsnag',
    author: 'Shayan',
    description: 'LogSnag Client',
    href: 'https://github.com/LogSnag/logsnag.js/',
    title: 'LogSang',
    // icon: StopIcon,
  },
  {
    name: '@capgo/walletconnect',
    author: 'Martin Donadieu',
    description: 'WIP: Capacitor plugin for WalletConnect',
    href: 'N/A',
    title: 'WalletConnect',
    // icon: WalletIcon,
  },
  {
    name: '@capgo/capacitor-uploader',
    author: 'Martin Donadieu',
    description: 'Background Uploader for capacitor apps',
    href: 'https://github.com/Cap-go/capacitor-uploader/',
    title: 'Uploader',
  },
  {
    name: '@revenuecat/purchases-capacitor',
    author: 'RevenueCat',
    description: 'In-app Subscriptions Made Easy with RevenueCat sdk',
    href: 'https://github.com/RevenueCat/purchases-capacitor/',
    title: 'Purchases',
  },
  {
    name: '@capgo/capacitor-data-storage-sqlite',
    author: 'Martin Donadieu',
    description: 'Capacitor SQLite Storage',
    href: 'https://github.com/Cap-go/capacitor-data-storage-sqlite/',
    title: 'Data Storage',
  },
  {
    name: '@capgo/capacitor-android-usagestatsmanager',
    author: 'Martin Donadieu',
    description: 'Capacitor plugin for android usage stats manager',
    href: 'https://github.com/Cap-go/capacitor-android-usagestatsmanager/',
    title: 'Usage Stats Manager',
  },
  {
    name: '@capgo/capacitor-streamcall',
    author: 'Martin Donadieu',
    description: 'Capacitor plugin for streamcall',
    href: 'https://github.com/Cap-go/capacitor-streamcall/',
    title: 'Streamcall',
  },
  {
    name: '@capgo/capacitor-autofill-save-password',
    author: 'Martin Donadieu',
    description: 'Capacitor plugin for save password in autofill of the device',
    href: 'https://github.com/Cap-go/capacitor-autofill-save-password/',
    title: 'Autofill Save Password',
  },
  {
    name: '@capgo/capacitor-social-login',
    author: 'Martin Donadieu',
    description: 'Capacitor plugin for social login',
    href: 'https://github.com/Cap-go/capacitor-social-login/',
    title: 'Social Login',
  },
  {
    name: '@capgo/capacitor-jw-player',
    author: 'Martin Donadieu',
    description: 'Capacitor plugin for jw player',
    href: 'https://github.com/Cap-go/capacitor-jw-player/',
    title: 'JW Player',
  },
  {
    name: '@capgo/capacitor-ricoh360-camera-plugin',
    author: 'Martin Donadieu',
    description: 'Capacitor plugin for ricoh360 camera',
    href: 'https://github.com/Cap-go/capacitor-ricoh360-camera-plugin/',
    title: 'Ricoh360 Camera',
  },
  {
    name: '@capgo/capacitor-admob',
    author: 'Martin Donadieu',
    description: 'AdMob integration for Capacitor apps',
    href: 'https://github.com/Cap-go/capacitor-admob/',
    title: 'AdMob',
  },
  {
    name: '@capgo/capacitor-alarm',
    author: 'Martin Donadieu',
    description: 'Schedule native alarms and notifications even when app is closed',
    href: 'https://github.com/Cap-go/capacitor-alarm/',
    title: 'Alarm',
  },
  {
    name: '@capgo/capacitor-android-inline-install',
    author: 'Martin Donadieu',
    description: 'Enable inline app installation on Android devices',
    href: 'https://github.com/Cap-go/capacitor-android-inline-install/',
    title: 'Android Inline Install',
  },
  {
    name: '@capgo/capacitor-appinsights',
    author: 'Martin Donadieu',
    description: 'Application insights and analytics using the Apptopia AppInsights SDK',
    href: 'https://github.com/Cap-go/capacitor-appinsights/',
    title: 'AppInsights',
  },
  {
    name: '@capgo/capacitor-audiosession',
    author: 'Martin Donadieu',
    description: 'Audio session management for iOS',
    href: 'https://github.com/Cap-go/capacitor-audiosession/',
    title: 'Audio Session',
  },
  {
    name: '@capgo/capacitor-background-geolocation',
    author: 'Martin Donadieu',
    description: 'Track device location in background with battery optimization',
    href: 'https://github.com/Cap-go/capacitor-background-geolocation/',
    title: 'Background Geolocation',
  },
  {
    name: '@capgo/capacitor-document-scanner',
    author: 'Martin Donadieu',
    description: 'Document scanning capabilities for mobile apps',
    href: 'https://github.com/Cap-go/capacitor-document-scanner/',
    title: 'Document Scanner',
  },
  {
    name: '@capgo/capacitor-downloader',
    author: 'Martin Donadieu',
    description: 'Background file downloads with progress tracking',
    href: 'https://github.com/Cap-go/capacitor-downloader/',
    title: 'Downloader',
  },
  {
    name: '@capgo/capacitor-env',
    author: 'Martin Donadieu',
    description: 'Environment variables management for Capacitor apps',
    href: 'https://github.com/Cap-go/capacitor-env/',
    title: 'Env',
  },
  {
    name: '@capgo/capacitor-ffmpeg',
    author: 'Martin Donadieu',
    description: 'Video encoding and processing powered by FFmpeg for compression and conversion',
    href: 'https://github.com/Cap-go/capacitor-ffmpeg/',
    title: 'FFmpeg',
  },
  {
    name: '@capgo/capacitor-gtm',
    author: 'Martin Donadieu',
    description: 'Google Tag Manager integration for analytics and tracking',
    href: 'https://github.com/Cap-go/capacitor-gtm/',
    title: 'GTM',
  },
  {
    name: '@capgo/capacitor-health',
    author: 'Martin Donadieu',
    description: 'Access health and fitness data from native health platforms',
    href: 'https://github.com/Cap-go/capacitor-health/',
    title: 'Health',
  },
  {
    name: '@capgo/capacitor-is-root',
    author: 'Martin Donadieu',
    description: 'Detect if device is rooted or jailbroken for security',
    href: 'https://github.com/Cap-go/capacitor-is-root/',
    title: 'Is Root',
  },
  {
    name: '@capgo/capacitor-launch-navigator',
    author: 'Martin Donadieu',
    description: 'Launch navigation apps with addresses and coordinates',
    href: 'https://github.com/Cap-go/capacitor-launch-navigator/',
    title: 'Launch Navigator',
  },
  {
    name: '@capgo/capacitor-live-reload',
    author: 'Martin Donadieu',
    description: 'Connect to your dev server for instant hot reloading during development',
    href: 'https://github.com/Cap-go/capacitor-live-reload/',
    title: 'Live Reload',
  },
  {
    name: '@capgo/capacitor-llm',
    author: 'Martin Donadieu',
    description: 'Run Large Language Models locally with Apple Intelligence support',
    href: 'https://github.com/Cap-go/capacitor-llm/',
    title: 'LLM',
  },
  {
    name: '@capgo/capacitor-media-session',
    author: 'Martin Donadieu',
    description: 'Control media playback from lock screen and notification center',
    href: 'https://github.com/Cap-go/capacitor-media-session/',
    title: 'Media Session',
  },
  {
    name: '@capgo/capacitor-mux-player',
    author: 'Martin Donadieu',
    description: 'Mux video player integration for high-quality streaming',
    href: 'https://github.com/Cap-go/capacitor-mux-player/',
    title: 'Mux Player',
  },
  {
    name: '@capgo/capacitor-pay',
    author: 'Martin Donadieu',
    description: 'Apple Pay and Google Pay integration for mobile payments',
    href: 'https://github.com/Cap-go/capacitor-pay/',
    title: 'Pay',
  },
  {
    name: '@capgo/capacitor-pdf-generator',
    author: 'Martin Donadieu',
    description: 'Generate PDF documents from HTML content',
    href: 'https://github.com/Cap-go/capacitor-pdf-generator/',
    title: 'PDF Generator',
  },
  {
    name: '@capgo/capacitor-persistent-account',
    author: 'Martin Donadieu',
    description: 'Maintain user accounts across app reinstalls',
    href: 'https://github.com/Cap-go/capacitor-persistent-account/',
    title: 'Persistent Account',
  },
  {
    name: '@capgo/capacitor-photo-library',
    author: 'Martin Donadieu',
    description: 'Access and manage device photo library',
    href: 'https://github.com/Cap-go/capacitor-photo-library/',
    title: 'Photo Library',
  },
  {
    name: '@capgo/capacitor-sim',
    author: 'Martin Donadieu',
    description: 'Access SIM card information and carrier details',
    href: 'https://github.com/Cap-go/capacitor-sim/',
    title: 'SIM',
  },
  {
    name: '@capgo/capacitor-textinteraction',
    author: 'Martin Donadieu',
    description: 'Enhanced text interaction and selection features',
    href: 'https://github.com/Cap-go/capacitor-textinteraction/',
    title: 'Text Interaction',
  },
  {
    name: '@capgo/capacitor-twilio-voice',
    author: 'Martin Donadieu',
    description: 'Make and receive phone calls using Twilio Voice API',
    href: 'https://github.com/Cap-go/capacitor-twilio-voice/',
    title: 'Twilio Voice',
  },
  {
    name: '@capgo/capacitor-video-player',
    author: 'Martin Donadieu',
    description: 'Native video playback with subtitles, fullscreen, and comprehensive controls',
    href: 'https://github.com/Cap-go/capacitor-video-player/',
    title: 'Video Player',
  },
  {
    name: '@capgo/capacitor-volume-buttons',
    author: 'Martin Donadieu',
    description: 'Listen to hardware volume button presses for custom controls',
    href: 'https://github.com/Cap-go/capacitor-volume-buttons/',
    title: 'Volume Buttons',
  },
  {
    name: '@capgo/capacitor-youtube-player',
    author: 'Martin Donadieu',
    description: 'Embed YouTube videos with full player API control and event handling',
    href: 'https://github.com/Cap-go/capacitor-youtube-player/',
    title: 'YouTube Player',
  },
]
