#!/usr/bin/env bun

/**
 * Generates a markdown file with plugin cards for use in GitHub org README.
 * Displays plugins in rows of 3 with name, description, npm downloads, and github stars.
 * Run with: bun run scripts/generate-plugins-readme.ts
 */

import { actions } from '../src/config/plugins'

// Load the data files
const starsPath = new URL('../src/data/github-stars.json', import.meta.url).pathname
const downloadsPath = new URL('../src/data/npm-downloads.json', import.meta.url).pathname

const githubStars: Record<string, number> = await Bun.file(starsPath).json()
const npmDownloads: Record<string, number> = await Bun.file(downloadsPath).json()

// Format numbers with K/M suffix
const formatNumber = (num: number): string => {
  if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`
  if (num >= 1000) return `${(num / 1000).toFixed(1)}K`
  return num.toString()
}

// Filter only @capgo/ plugins
const capgoPlugins = actions.filter(
  (plugin) => plugin.author === 'github.com/Cap-go' && plugin.name?.startsWith('@capgo/')
)

// Sort by GitHub stars (most popular first)
const sortedPlugins = [...capgoPlugins].sort((a, b) => {
  const aStars = githubStars[a.href] || 0
  const bStars = githubStars[b.href] || 0
  return bStars - aStars
})

type CardData = Pick<(typeof actions)[0], 'title' | 'href' | 'description'> & {
  name?: string
  code?: string
  npmPackage?: string
  docsUrl?: string
  width?: string
}

const capgoCloudCards: CardData[] = [
  {
    title: 'Updater',
    name: '@capgo/capacitor-updater',
    href: 'https://github.com/Cap-go/capacitor-updater/',
    description: 'Deploy live updates instantly to your users without app store review delays',
    docsUrl: 'https://capgo.app/plugins/updater/',
  },
  {
    title: 'Capgo Console',
    code: 'Capgo Console',
    href: 'https://github.com/Cap-go/capgo/',
    description: 'Front and back base on Supabase',
    docsUrl: 'https://capgo.app/docs/',
  },
  {
    title: 'Capgo CLI',
    name: '@capgo/cli',
    href: 'https://github.com/Cap-go/cli/',
    description: 'Manage/Upload your Cloud/ Self hosted apps from CLI',
    docsUrl: 'https://capgo.app/docs/cli/',
  },
]

// Generate HTML table rows (3 plugins per row)
const generatePluginCard = (card: CardData): string => {
  const code = card.code ?? card.name
  const npmPackage = card.npmPackage ?? card.name
  const npmUrl = npmPackage ? `https://www.npmjs.com/package/${npmPackage}` : undefined
  const docsUrl =
    card.docsUrl ?? `https://capgo.app/plugins/${card.title.toLowerCase().replace(/\s+/g, '-')}/`
  const repoPath = card.href.replace('https://github.com/', '').replace(/\/$/, '').split('/tree/')[0]

  const badges: string[] = []
  if (npmUrl && npmPackage) {
    badges.push(
      `<a href="${npmUrl}"><img src="https://img.shields.io/npm/dw/${npmPackage}?style=flat-square&label=downloads" alt="npm downloads"></a>`
    )
  }
  badges.push(
    `<a href="${card.href}"><img src="https://img.shields.io/github/stars/${repoPath}?style=flat-square&label=stars" alt="GitHub stars"></a>`
  )

  const links: string[] = []
  if (docsUrl) {
    links.push(`<a href="${docsUrl}">Docs</a>`)
  }
  links.push(`<a href="${card.href}">GitHub</a>`)

  return `<td align="center" width="${card.width ?? '33%'}">
<h3><a href="${card.href}">${card.title}</a></h3>
${code ? `<p><code>${code}</code></p>` : ''}
<p>${card.description}</p>
<p>
${badges.join('\n')}
</p>
<p>${links.join(' | ')}</p>
</td>`
}

// Generate awesome list card (same style as plugins)
const generateAwesomeCard = (
  title: string,
  description: string,
  username: string,
  repo: string,
  href: string
): string => {
  return `<td align="center" width="50%">
<h3><a href="${href}">${title}</a></h3>
<p>${description}</p>
<p>
<a href="${href}"><img src="https://img.shields.io/github/stars/${username}/${repo}?style=flat-square&label=stars" alt="GitHub stars"></a>
<a href="${href}"><img src="https://img.shields.io/github/forks/${username}/${repo}?style=flat-square&label=forks" alt="GitHub forks"></a>
</p>
<p><a href="${href}">GitHub</a></p>
</td>`
}

const capgoCloudSection = `<table>
<tr>
${capgoCloudCards.map((card) => generatePluginCard(card)).join('\n')}
</tr>
</table>`

// Build the markdown content
let markdown = `<!-- AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY -->
<!-- Generated by: bun run generate:plugins-readme -->
<!-- Last updated: ${new Date().toISOString()} -->

<h1 align="left">Welcome to <a href="https://capgo.app">Capgo</a>!</h1>

<p align="left">
Capgo is the Expo for Capacitor, providing SDKs, plugins, cloud updates, and native builds for any web framework. Fast on Web, on Native only when needed.
</p>

[Read the documentation to get started](https://capgo.app/docs/)

## Community

💬 Join us on [Discord](https://discord.capgo.app) to chat with the Capgo community, discuss the release, or ask questions.

## Community Plugin Option

Got a plugin and want to keep building without carrying maintenance alone? We can host it under the Capgo name and share maintenance with you.

- Co-maintained with the original open-source maintainer and Capgo
- Better visibility through Capgo distribution and ecosystem reach
- Shared maintenance burden so plugins stay healthy over time
- Capgo support on quality standards, release process, CI, and maintenance best practices
- Original makers keep owning the direction while getting operational support
- Examples already in this model: [Background Geolocation](https://github.com/Cap-go/capacitor-background-geolocation/), [Social Login](https://github.com/Cap-go/capacitor-social-login/), and [In App Browser](https://github.com/Cap-go/capacitor-inappbrowser/)

We are pro AI and welcome AI contributions.
Our philosophy: build fast, fix fast.
Contact us to co-maintain your plugin: [martin@capgo.app](mailto:martin@capgo.app)

## Who’s using Capgo?

Capgo is trusted by teams worldwide, from startups to large companies building production Capacitor apps.  
Explore real-world apps using Capgo in production in the [Showcase](https://capgo.app/top_capacitor_app/).

[![Open Bounties](https://img.shields.io/endpoint?url=https%3A%2F%2Fconsole.algora.io%2Fapi%2Fshields%2FCapgo%2Fbounties%3Fstatus%3Dopen)](https://console.algora.io/org/Capgo/bounties?status=open)
[![Rewarded Bounties](https://img.shields.io/endpoint?url=https%3A%2F%2Fconsole.algora.io%2Fapi%2Fshields%2FCapgo%2Fbounties%3Fstatus%3Dcompleted)](https://console.algora.io/org/Capgo/bounties?status=completed)
[![Discord](https://badgen.net/badge/icon/discord?icon=discord&label)](https://discord.com/invite/VnYRvBfgA6)
[![Npm](https://badgen.net/badge/icon/npm?icon=npm&label)](https://www.npmjs.com/search?q=%40capgo)
[![Twitter](https://badgen.net/badge/icon/twitter?icon=twitter&label)](https://twitter.com/Capgo_app)
[![https://good-labs.github.io/greater-good-affirmation/assets/images/badge.svg](https://good-labs.github.io/greater-good-affirmation/assets/images/badge.svg)](https://good-labs.github.io/greater-good-affirmation)

## Awesome Lists

<table>
<tr>
${generateAwesomeCard('Awesome Ionic', 'A curated list of awesome Ionic libraries, resources, and solutions', 'Cap-go', 'awesome-ionic', 'https://github.com/Cap-go/awesome-ionic')}
${generateAwesomeCard('Awesome Capacitor', 'A curated list of awesome Capacitor plugins, tools, and resources', 'riderx', 'awesome-capacitor', 'https://github.com/riderx/awesome-capacitor')}
</tr>
</table>

## Capgo Cloud

${capgoCloudSection}

## Capacitor Plugins

A collection of high-quality Capacitor plugins maintained by [Capgo](https://capgo.app).

**Total Plugins:** ${sortedPlugins.length} | **Weekly Downloads:** ${formatNumber(
  Object.values(npmDownloads).reduce((sum, d) => sum + d, 0)
)} | **GitHub Stars:** ${formatNumber(Object.values(githubStars).reduce((sum, s) => sum + s, 0))}

<table>
`

// Generate rows of 3
for (let i = 0; i < sortedPlugins.length; i += 3) {
  markdown += '<tr>\n'
  for (let j = 0; j < 3; j++) {
    const plugin = sortedPlugins[i + j]
    if (plugin) {
      markdown += generatePluginCard(plugin) + '\n'
    } else {
      markdown += '<td></td>\n'
    }
  }
  markdown += '</tr>\n'
}

markdown += `</table>

---

## Quick Links

- [All Plugins](https://capgo.app/plugins/) - Browse all plugins with search and filtering
- [Documentation](https://capgo.app/docs/) - Full documentation and guides
- [Capgo Live Updates](https://capgo.app/) - Deploy live updates to your Capacitor apps

## Contributing

We welcome contributions! Please see the individual plugin repositories for contribution guidelines.

## License

All plugins are released under the Mozilla Public License Version 2.0 unless mentioned otherwise.

## Stargazers over time

[![Stargazers over time](https://starchart.cc/Cap-go/capacitor-updater.svg)](https://starchart.cc/Cap-go/capacitor-updater)
`

// Write to public directory so it can be served
const outputPath = new URL('../public/plugins-readme.md', import.meta.url).pathname
await Bun.write(outputPath, markdown)

console.log(`Generated plugins README with ${sortedPlugins.length} plugins`)
console.log(`Output: ${outputPath}`)
