import { appendFileSync, readdirSync, readFileSync, writeFileSync } from 'fs'
import { load } from 'js-yaml'
import { join } from 'path'

const translationLocales: string[] = []
const translations: { [k: string]: { [r: string]: string } } = {}

const loadYmlFiles = (directory: string) => {
  const files = readdirSync(directory)
  files.forEach((file) => {
    const fileName = file.split('.')
    translationLocales.push(fileName[0])
    if (fileName[1] === 'yml') {
      const filePath = join(directory, file)
      const content = readFileSync(filePath, 'utf8')
      const data = load(content) as { [p: string]: string }
      Object.keys(data).forEach((key) => {
        if (translations[key]) {
          translations[key] = {
            ...translations[key],
            [fileName[0]]: data[key],
          }
        } else {
          translations[key] = {
            [fileName[0]]: data[key],
          }
        }
      })
    }
  })
}

loadYmlFiles(join(process.cwd(), 'locales'))

const translationFile = join(process.cwd(), 'src', 'services', 'translations.ts')

console.log(`Writing to src/services/translations.ts with all the locale ymls as JSONs...`)
writeFileSync(translationFile, '// Do not edit this file\n// Auto-generated from generate_translation_ts_file.tsx code\n', { encoding: 'utf8' })
appendFileSync(translationFile, 'export default ', { encoding: 'utf8' })
appendFileSync(translationFile, JSON.stringify(translations), { encoding: 'utf8' })
console.log(`Done.\n`)

const localeFile = join(process.cwd(), 'src', 'services', 'locale.ts')

console.log(`Writing to src/services/locale.ts all the locales from the locales directory...`)
writeFileSync(localeFile, '// Do not edit this file\n// Auto-generated from generate_translation_ts_file.tsx code\n', { encoding: 'utf8' })
appendFileSync(localeFile, `export const locales = ${JSON.stringify(translationLocales)}\n`, { encoding: 'utf8' })
appendFileSync(localeFile, `export type Locales = "${translationLocales.join('" | "')}"\nexport const defaultLocale = 'en'`, { encoding: 'utf8' })
console.log(`Done.\n`)
