#!/usr/bin/env bun

/**
 * Generates a markdown file with plugin cards for use in GitHub org README.
 * Displays plugins in rows of 3 with name, description, npm downloads, and github stars.
 * Run with: bun run scripts/generate-plugins-readme.ts
 */

import { actions } from '../src/config/plugins'

// Load the data files
const starsPath = new URL('../src/data/github-stars.json', import.meta.url).pathname
const downloadsPath = new URL('../src/data/npm-downloads.json', import.meta.url).pathname

const githubStars: Record<string, number> = await Bun.file(starsPath).json()
const npmDownloads: Record<string, number> = await Bun.file(downloadsPath).json()

// Format numbers with K/M suffix
const formatNumber = (num: number): string => {
  if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`
  if (num >= 1000) return `${(num / 1000).toFixed(1)}K`
  return num.toString()
}

// Filter only @capgo/ plugins
const capgoPlugins = actions.filter(
  (plugin) => plugin.author === 'github.com/Cap-go' && plugin.name?.startsWith('@capgo/')
)

// Sort by GitHub stars (most popular first)
const sortedPlugins = [...capgoPlugins].sort((a, b) => {
  const aStars = githubStars[a.href] || 0
  const bStars = githubStars[b.href] || 0
  return bStars - aStars
})

// Generate HTML table rows (3 plugins per row)
const generatePluginCard = (plugin: (typeof actions)[0]): string => {
  const npmUrl = plugin.name ? `https://www.npmjs.com/package/${plugin.name}` : '#'
  const docsUrl = `https://capgo.app/plugins/${plugin.title.toLowerCase().replace(/\s+/g, '-')}/`
  const repoPath = plugin.href.replace('https://github.com/', '').replace(/\/$/, '').split('/tree/')[0]

  return `<td align="center" width="33%">
<h3><a href="${plugin.href}">${plugin.title}</a></h3>
<p><code>${plugin.name}</code></p>
<p>${plugin.description}</p>
<p>
<a href="${npmUrl}"><img src="https://img.shields.io/npm/dw/${plugin.name}?style=flat-square&label=downloads" alt="npm downloads"></a>
<a href="${plugin.href}"><img src="https://img.shields.io/github/stars/${repoPath}?style=flat-square&label=stars" alt="GitHub stars"></a>
</p>
<p><a href="${docsUrl}">Docs</a> | <a href="${plugin.href}">GitHub</a></p>
</td>`
}

// Generate awesome list card (same style as plugins)
const generateAwesomeCard = (
  title: string,
  description: string,
  username: string,
  repo: string,
  href: string
): string => {
  return `<td align="center" width="50%">
<h3><a href="${href}">${title}</a></h3>
<p>${description}</p>
<p>
<a href="${href}"><img src="https://img.shields.io/github/stars/${username}/${repo}?style=flat-square&label=stars" alt="GitHub stars"></a>
<a href="${href}"><img src="https://img.shields.io/github/forks/${username}/${repo}?style=flat-square&label=forks" alt="GitHub forks"></a>
</p>
<p><a href="${href}">GitHub</a></p>
</td>`
}

// Build the markdown content
let markdown = `<!-- AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY -->
<!-- Generated by: bun run generate:plugins-readme -->
<!-- Last updated: ${new Date().toISOString()} -->

<h1 align="left">Welcome to the <a href="https://capgo.app">Capgo</a> community!</h1>
<p align='center'>
  <img src='https://raw.githubusercontent.com/Cap-go/capgo/main/assets/capgo_banner.png' alt='Capgo - Instant updates for capacitor'/>
</p>
<br/>
<div align="center">
  <h2><a href="https://capgo.app/?ref=plugin"> ➡️ Get Instant updates for your App with Capgo </a></h2>
  <h2><a href="https://capgo.app/consulting/?ref=plugin"> Missing a feature? We'll build the plugin for you 💪</a></h2>
</div>
<br/>

[![Open Bounties](https://img.shields.io/endpoint?url=https%3A%2F%2Fconsole.algora.io%2Fapi%2Fshields%2FCapgo%2Fbounties%3Fstatus%3Dopen)](https://console.algora.io/org/Capgo/bounties?status=open)
[![Rewarded Bounties](https://img.shields.io/endpoint?url=https%3A%2F%2Fconsole.algora.io%2Fapi%2Fshields%2FCapgo%2Fbounties%3Fstatus%3Dcompleted)](https://console.algora.io/org/Capgo/bounties?status=completed)
[![Discord](https://badgen.net/badge/icon/discord?icon=discord&label)](https://discord.com/invite/VnYRvBfgA6)
[![Npm](https://badgen.net/badge/icon/npm?icon=npm&label)](https://www.npmjs.com/search?q=%40capgo)
[![Twitter](https://badgen.net/badge/icon/twitter?icon=twitter&label)](https://twitter.com/Capgo_app)
![npm](https://img.shields.io/npm/dm/@capgo/capacitor-updater)
[![GitHub latest commit](https://badgen.net/github/last-commit/Cap-go/capacitor-updater/main)](https://GitHub.com/Cap-go/capacitor-updater/commit/)
[![https://good-labs.github.io/greater-good-affirmation/assets/images/badge.svg](https://good-labs.github.io/greater-good-affirmation/assets/images/badge.svg)](https://good-labs.github.io/greater-good-affirmation)

## Awesome Lists

<table>
<tr>
${generateAwesomeCard('Awesome Ionic', 'A curated list of awesome Ionic libraries, resources, and solutions', 'Cap-go', 'awesome-ionic', 'https://github.com/Cap-go/awesome-ionic')}
${generateAwesomeCard('Awesome Capacitor', 'A curated list of awesome Capacitor plugins, tools, and resources', 'riderx', 'awesome-capacitor', 'https://github.com/riderx/awesome-capacitor')}
</tr>
</table>

## Capacitor Plugins

A collection of high-quality Capacitor plugins maintained by [Capgo](https://capgo.app).

**Total Plugins:** ${sortedPlugins.length} | **Weekly Downloads:** ${formatNumber(
  Object.values(npmDownloads).reduce((sum, d) => sum + d, 0)
)} | **GitHub Stars:** ${formatNumber(Object.values(githubStars).reduce((sum, s) => sum + s, 0))}

<table>
`

// Generate rows of 3
for (let i = 0; i < sortedPlugins.length; i += 3) {
  markdown += '<tr>\n'
  for (let j = 0; j < 3; j++) {
    const plugin = sortedPlugins[i + j]
    if (plugin) {
      markdown += generatePluginCard(plugin) + '\n'
    } else {
      markdown += '<td></td>\n'
    }
  }
  markdown += '</tr>\n'
}

markdown += `</table>

---

## Quick Links

- [All Plugins](https://capgo.app/plugins/) - Browse all plugins with search and filtering
- [Documentation](https://capgo.app/docs/) - Full documentation and guides
- [Capgo Live Updates](https://capgo.app/) - Deploy live updates to your Capacitor apps

## Contributing

We welcome contributions! Please see the individual plugin repositories for contribution guidelines.

## License

All plugins are released under the Mozilla Public License Version 2.0 unless mentioned otherwise.

## Stargazers over time

[![Stargazers over time](https://starchart.cc/Cap-go/capacitor-updater.svg)](https://starchart.cc/Cap-go/capacitor-updater)
`

// Write to public directory so it can be served
const outputPath = new URL('../public/plugins-readme.md', import.meta.url).pathname
await Bun.write(outputPath, markdown)

console.log(`Generated plugins README with ${sortedPlugins.length} plugins`)
console.log(`Output: ${outputPath}`)
