export type SecurityQuestionnaireItem = {
  id?: string
  question: string
  answer: string
}

export type SecurityQuestionnaireSection = {
  id: string
  title: string
  items: SecurityQuestionnaireItem[]
}

/** Approved enterprise vendor security questionnaire answers (October 2026). English source for legal accuracy. */
export const enterpriseQuestionnaireSections: SecurityQuestionnaireSection[] = [
  {
    id: 'qa-access',
    title: 'Access control and identity',
    items: [
      {
        id: 'AC.11',
        question: 'Is a VPN required for remote access to your network?',
        answer:
          'No. There is no corporate network to connect to. Staff manage production through cloud provider consoles and APIs over TLS with enforced MFA. Production database and SSH access are not exposed to the public internet.',
      },
      {
        id: 'AC.12',
        question: 'Is automatic screen lock with password re-authentication enforced within 15 minutes or less?',
        answer: 'Yes. Automatic screen lock with password re-authentication is enforced and monitored on all endpoints through our device compliance agent.',
      },
      {
        id: 'AC.13',
        question: 'Is access provisioned with role-based, least-privilege controls and approval before credentials are issued?',
        answer: 'Yes. Access is provisioned through role-based access control on a least-privilege basis and requires approval before credentials are issued.',
      },
      {
        id: 'AC.14',
        question: 'Is access reviewed when a user changes role?',
        answer: 'Yes. Our compliance monitoring platform alerts the security owner to update access whenever a role changes, and all access is also reviewed periodically.',
      },
      {
        id: 'AC.15',
        question: 'Is there an industry-standard password policy owned by security leadership and approved annually?',
        answer: 'Yes. Our documented password and login policy is owned by the Information Security Officer and reviewed and approved annually by senior management.',
      },
      {
        id: 'AC.16',
        question: 'Must users reset or set their own password at first sign-on?',
        answer:
          'Yes. We do not issue reusable initial passwords. New users receive a single-use invitation or temporary credential and must set their own password at first sign-in, with MFA required.',
      },
      {
        id: 'AC.17',
        question: 'Are initial passwords or invitation links randomly generated and unique per user?',
        answer: 'Yes. Invitation links and any temporary credentials are randomly generated and unique to each user.',
      },
      {
        id: 'AC.18',
        question: 'Are vendor default accounts and settings changed before production use?',
        answer:
          'Yes. Production runs on managed serverless services without vendor default accounts, and default settings are reviewed and hardened under our configuration management controls before use.',
      },
      {
        id: 'AC.22',
        question: 'Do you use a centralized directory service for workforce identity?',
        answer:
          'Yes. Google Workspace is our central identity directory, with 2-Step Verification enforced for all accounts, and is used for sign-in to core systems where supported.',
      },
      {
        id: 'AC.23',
        question: 'Do passwords expire on a fixed schedule?',
        answer:
          'No fixed rotation. Following NIST SP 800-63B, passwords are not rotated on a fixed schedule. They are changed on any sign of compromise, and MFA is enforced on all systems.',
      },
      {
        id: 'AC.24',
        question: 'Do workforce passwords require at least 8 characters with upper, lower, number, and special character?',
        answer: 'Yes for workforce accounts through our identity provider settings, with MFA required on all systems.',
      },
      {
        id: 'AC.25',
        question: 'Is password history enforced?',
        answer: 'No fixed history rule for workforce passwords. Reuse risk is addressed by MFA on all systems and unique passwords generated by a password manager.',
      },
      {
        id: 'AC.25.1',
        question: 'Are commonly used passwords blocked automatically?',
        answer: 'Yes. Our identity provider rejects weak and commonly used passwords.',
      },
      {
        id: 'AC.29',
        question: 'Can only registered, compliant devices access internal systems?',
        answer:
          'There is no corporate network. Internal systems are accessed only from inventoried, registered endpoints that pass device compliance checks for encryption, malware protection, patching, and screen lock.',
      },
      {
        id: 'AC.30',
        question: 'Are dormant accounts disabled automatically after inactivity?',
        answer:
          'No inactivity timer. Access is removed within 1 business day of offboarding, and periodic access reviews by the Information Security Officer identify and remove unused accounts.',
      },
      {
        id: 'HAS.20',
        question: 'Is MFA enforced for all staff with remote production administrative access?',
        answer: 'Yes. MFA is enforced for all staff accounts with access to production and other critical systems.',
      },
      {
        id: 'HAS.20.1',
        question: 'Is MFA available and enforceable for all Capgo Cloud application users?',
        answer:
          'Yes. TOTP MFA is available to every user, and organization administrators can enforce it for all members, which blocks dashboard and CLI access for anyone without MFA.',
      },
      {
        id: 'HAS.27',
        question: 'What sign-in methods does the Capgo Cloud console support?',
        answer:
          'Users sign in with email and password plus TOTP MFA, which customers can enforce for all members. SAML 2.0 SSO with optional enforcement is available on the Enterprise plan. CLI and CI access uses scoped API keys with optional mandatory expiry.',
      },
      {
        id: 'HAS.35',
        question: 'Are accounts locked out after a fixed number of failed login attempts?',
        answer: 'No fixed per-account lockout. Sign-in attempts are rate limited by our authentication provider, and customers can enforce MFA or SAML SSO for all of their users.',
      },
      {
        id: 'HAS.30',
        question: 'Do privileged staff have direct production database access?',
        answer:
          'Yes, but limited. Direct production database access is limited to 2 authorized engineers, protected by MFA, not exposed to the public internet, and reviewed periodically.',
      },
      {
        id: 'OS.3',
        question: 'Who is accountable for security functions?',
        answer:
          'The CEO is the designated Information Security Officer, accountable for security policy, governance, strategy, threat and vulnerability management, and incident response, supported by the engineering team.',
      },
    ],
  },
  {
    id: 'qa-endpoints',
    title: 'Endpoint and asset management',
    items: [
      {
        id: 'AM.2.1',
        question: 'Does your asset inventory identify internet-facing systems?',
        answer: 'Yes. Our infrastructure inventory and architecture diagram identify all internet-facing endpoints.',
      },
      {
        id: 'AM.3',
        question: 'Is secure disposal of data and media governed by formal protocols?',
        answer:
          'Yes. Disposal follows our Data Classification, Retention, and Deletion Policy. Destruction of storage media in data centers is performed by our cloud providers under their audited controls.',
      },
      {
        id: 'AM.5',
        question: 'Are security configuration baselines defined and reviewed at least every 12 months?',
        answer:
          'Yes. Configuration baselines for our cloud services and endpoints are defined under our configuration management controls and reviewed at least annually with our policies.',
      },
      {
        id: 'AM.6',
        question: 'Are operating systems hardened to necessary ports, protocols, and services?',
        answer:
          'Yes for production: serverless on managed platforms with ingress limited to HTTPS on designated endpoints and deny-by-default firewall rules. Scaleway macOS build runners are the main OS Capgo operates for native builds.',
      },
      {
        id: 'CO.4',
        question: 'What endpoint protections are deployed on staff devices?',
        answer:
          'All endpoints run malware protection and full-disk encryption, monitored by our device compliance agent. Host IPS and USB port blocking are not deployed. Customer data is processed in our cloud production systems.',
      },
      {
        id: 'CO.5',
        question: 'Is full-disk encryption deployed on staff endpoints?',
        answer:
          'Yes. Full-disk encryption is enforced and monitored on all endpoints. Databases and cloud backups are encrypted at rest in our cloud providers. We do not write backups to removable media.',
      },
      {
        id: 'CO.5.1',
        question: 'Do you operate a DLP tool that monitors outbound traffic and USB?',
        answer:
          'No. Customer data stays in access-controlled cloud systems, endpoints are fully encrypted and monitored, and data handling rules are defined in our Acceptable Use and Data Classification policies.',
      },
      {
        id: 'CO.8',
        question: 'Are firewall rules reviewed or recertified regularly?',
        answer:
          'Yes. Production ingress rules are deny-by-default and limited to HTTPS endpoints, and are reviewed at least annually as part of our configuration and access reviews.',
      },
      {
        id: 'CO.9',
        question: 'Do you maintain network diagrams showing inbound and outbound connections?',
        answer:
          'Yes. Our architecture and network diagrams show system boundaries and the connections between Capgo, our cloud providers, and customers, and are maintained with the system inventory.',
      },
      {
        id: 'CO.14',
        question: 'May staff read corporate email on personal computers?',
        answer:
          'Staff may use registered personal laptops enrolled in our device compliance agent, which enforces disk encryption, malware protection, screen lock, and patching. Email access requires MFA.',
      },
      {
        id: 'CO.15',
        question: 'Is MFA required for remote access to corporate email?',
        answer: 'Yes. 2-Step Verification is enforced at the domain level for all Google Workspace accounts.',
      },
      {
        id: 'CO.16',
        question: 'How often must users re-authenticate with MFA?',
        answer:
          'MFA is required at every new sign-in and on any new device. Session length follows our Google Workspace session control setting (currently 14 days for trusted sessions).',
      },
    ],
  },
  {
    id: 'qa-hosting-tenant',
    title: 'Hosting, application security, and tenant isolation',
    items: [
      {
        id: 'HAS.7',
        question: 'What URL do customers use to access the hosted application?',
        answer: 'https://console.capgo.app',
      },
      {
        id: 'HAS.8',
        question: 'Where is the service hosted?',
        answer:
          'At cloud service providers: serverless on Cloudflare Workers with managed Supabase PostgreSQL in London, Google Cloud read replicas, and Scaleway in Paris for native builds. See the subprocessors page for the current list.',
      },
      {
        id: 'HAS.9',
        question: 'Is the service hosted in colocation facilities you operate?',
        answer: 'No. Capgo does not operate colocation or owned data centers.',
      },
      {
        id: 'HAS.10',
        question: 'How is customer data separated in the multi-tenant service?',
        answer:
          'Logical multi-tenant separation. Database records are isolated per organization by PostgreSQL Row Level Security and role-based authorization. Bundles are stored in object storage under per-organization and per-app paths. Customers can enable end-to-end bundle encryption with their own keys.',
      },
      {
        id: 'HAS.11',
        question: 'Does each customer receive separate database credentials or schemas?',
        answer: 'No separate database per customer. Tenant isolation is enforced by Row Level Security and application authorization rather than per-tenant database credentials.',
      },
      {
        id: 'HAS.21',
        question: 'How do administrators manage production?',
        answer:
          'Through cloud provider web consoles and their CLIs and APIs over TLS, using MFA-protected accounts and scoped API tokens. Production database and SSH access are not exposed to the public internet.',
      },
      {
        id: 'HAS.28',
        question: 'Which common production controls are not in place?',
        answer:
          'We do not operate a dedicated SIEM or corporate VPN. Cloudflare provides DDoS protection and a web application firewall at the edge, production hosts are deny-by-default, and administrative access uses MFA-protected provider consoles.',
      },
      {
        id: 'HAS.31',
        question: 'Do databases run under non-privileged service accounts?',
        answer:
          'Yes. The database is managed PostgreSQL operated by Supabase. Application connections use dedicated non-superuser roles, and user-facing access is subject to Row Level Security.',
      },
      {
        id: 'HAS.32',
        question: 'Does the application tier run under a non-privileged service account?',
        answer: 'Yes. The web tier runs on Cloudflare Workers in sandboxed V8 isolates, with no operating system or root account exposed to our code.',
      },
    ],
  },
  {
    id: 'qa-encryption',
    title: 'Encryption (platform and customer options)',
    items: [
      {
        id: 'HAS.13',
        question: 'Is customer data encrypted at rest in databases and object storage?',
        answer:
          'Yes. Databases, backups, and object storage are encrypted at rest with AES-256 by our cloud providers, with keys stored and rotated in the providers key management systems. Customers can additionally encrypt bundles end to end with their own key pair.',
      },
      {
        id: 'HAS.14',
        question: 'Does each customer have a distinct encryption key for platform storage?',
        answer:
          'No for platform storage. Provider-managed keys are shared across tenants. For bundles, customers can enable end-to-end encryption with their own RSA key pair whose private key Capgo never holds.',
      },
      {
        id: 'HAS.15',
        question: 'Can personnel who access encrypted production data obtain encryption keys?',
        answer:
          'No for platform keys. Encryption keys for data at rest are held in our cloud providers key management systems and are not accessible to Capgo personnel. Private keys for end-to-end bundle encryption are held only by the customer.',
      },
      {
        id: 'HAS.16',
        question: 'Can customers supply customer-managed keys for platform storage encryption?',
        answer: 'No for platform storage. Customers can encrypt bundles end to end with their own key pair so Capgo does not hold the key for that content.',
      },
    ],
  },
  {
    id: 'qa-logging',
    title: 'Logging and monitoring',
    items: [
      {
        id: 'AC.26',
        question: 'Are audit logs retained for at least three years?',
        answer:
          'No. Audit events are generated for security-relevant actions on critical systems and reviewed with alerting to detect anomalous activity. Logs are retained according to our Logging Policy and each platform retention settings, which is less than three years.',
      },
      {
        id: 'AC.27.1',
        question: 'Do production logs feed a SIEM?',
        answer: 'No dedicated SIEM. Production logs are collected in our cloud providers logging and observability tools with alerting and are reviewed for anomalous activity.',
      },
      {
        id: 'CO.3',
        question: 'What network defenses and monitoring are in place?',
        answer:
          'Cloudflare provides edge firewall, web application firewall, and DDoS protection. Production hosts use deny-by-default rules, and Google Workspace filters email and spam. We do not operate a dedicated SIEM; logs are monitored with alerting in our providers tools.',
      },
    ],
  },
  {
    id: 'qa-vulnerability',
    title: 'Vulnerability management and penetration testing',
    items: [
      {
        id: 'HAS.4',
        question: 'What security testing is required before production release?',
        answer:
          'Every pull request runs automated tests, linting, static analysis (SonarCloud and a mandatory security scan), and automated code review before merge, and production changes are approved by management. DAST is not part of the release pipeline. An annual third-party penetration test covers the running application.',
      },
      {
        id: 'VM.7',
        question: 'What is the patching cadence for critical and high vulnerabilities?',
        answer: 'Critical: within 7 days. High: within 30 days, per our Vulnerability Management Policy.',
      },
    ],
  },
  {
    id: 'qa-incident',
    title: 'Incident response',
    items: [
      {
        id: 'IE.2',
        question: 'Does your incident response plan cover common incident types?',
        answer:
          'Yes. Our incident response plan covers malware, denial of service, unauthorized access, unauthorized physical access, data loss, lost laptops, and ransomware. Physical intrusion scenarios apply to endpoints only because we operate fully remote with no owned premises.',
      },
      {
        id: 'IE.3',
        question: 'Do you maintain a contracted incident response firm on retainer?',
        answer: 'No retainer today. Our incident response plan provides for engaging an external incident response firm when needed.',
      },
      {
        id: 'IE.3.2',
        question: 'Is the incident response plan tested and updated at least annually?',
        answer: 'Yes. The incident response plan is reviewed and approved annually by senior management, and we run an annual tabletop exercise.',
      },
      {
        id: 'IE.6',
        question: 'Is there a protocol for engaging law enforcement?',
        answer:
          'Yes. Our incident response policy defines notification of customers and other stakeholders, and we maintain contacts with relevant authorities, including law enforcement, as part of our ISO 27001 program.',
      },
    ],
  },
  {
    id: 'qa-hr',
    title: 'HR and personnel security',
    items: [
      {
        id: 'HR.2',
        question: 'Do you contractually require all vendors to perform background checks?',
        answer:
          'No. Our infrastructure vendors screen their own personnel under audited SOC 2 and ISO 27001 programs, which we review annually. All Capgo staff are background checked before access is granted.',
      },
      {
        id: 'HR.4',
        question: 'Do you run simulated phishing exercises at least annually?',
        answer: 'No. Phishing awareness is covered in onboarding and annual security training, and MFA is enforced on all accounts.',
      },
      {
        id: 'HR.6',
        question: 'Is return of assets and access removal documented at termination?',
        answer: 'Yes. Our termination checklist covers return of company assets and removal of all access within 1 business day.',
      },
    ],
  },
  {
    id: 'qa-physical',
    title: 'Physical and environmental security',
    items: [
      {
        id: 'PE.1',
        question: 'Do you maintain a physical security policy?',
        answer:
          'Yes, reviewed and approved annually. Capgo has no offices or data centers. The policy covers remote work, endpoints, and oversight of our cloud providers facilities.',
      },
      {
        id: 'PE.2',
        question: 'What physical controls protect your environment?',
        answer:
          'Capgo has no offices or data centers. All production runs in Cloudflare, Supabase, Google Cloud, and Scaleway facilities whose physical controls are covered by independent audits that we review annually.',
      },
      {
        id: 'PE.4',
        question: 'Are visitors permitted at your facilities?',
        answer: 'Not applicable at Capgo. We operate fully remote with no owned premises. Data center visitor controls are handled by our cloud providers.',
      },
    ],
  },
  {
    id: 'qa-continuity',
    title: 'Business continuity and backups',
    items: [
      {
        id: 'CO.6',
        question: 'Are backup recoveries tested at least annually?',
        answer: 'Yes. Backups are tested periodically for integrity and restorability, and recovery procedures are exercised annually.',
      },
    ],
  },
  {
    id: 'qa-gai',
    title: 'Generative AI',
    items: [
      {
        id: 'GAI.2',
        question: 'Do you use off-the-shelf generative AI tools that could process customer data?',
        answer:
          'Capgo uses AI coding assistants only for development on Capgo own source code, not on customer data. The customer-facing AI feature is an opt-in build-log diagnostic on Cloudflare Workers AI, an existing sub-processor. Data is processed per request and is not retained or used for training.',
      },
      {
        id: 'GAI.3',
        question: 'Is customer data sent outside your environment for AI analysis?',
        answer:
          'Customer data is not sent to external AI providers for analysis. If a customer opts in to AI-assisted build-log diagnostics, logs are processed per request on Cloudflare Workers AI and are not retained or used for training.',
      },
      {
        id: 'GAI.10',
        question: 'Do you test AI outputs for unfair or discriminatory outcomes?',
        answer: 'Not applicable. AI is used only for technical build-log diagnostics and internal development assistance, and makes no decisions about individuals.',
      },
      {
        id: 'GAI.11',
        question: 'Does AI processing avoid reliance on protected characteristics?',
        answer: 'Yes. The customer-facing AI feature processes technical build logs only and does not use personal or protected characteristics.',
      },
      {
        id: 'GAI.12',
        question: 'Is AI output governed with human review and monitoring?',
        answer:
          'Yes. Customer-facing AI output is advisory only and shown to the developer, who decides what to do. It takes no automated action. The feature is opt-in and covered by our risk assessment and vendor management processes.',
      },
      {
        id: 'GAI.13',
        question: 'Is access to AI components least privilege?',
        answer:
          'Yes. The AI feature runs inside our production platform under the same role-based, least-privilege access controls, and the model service does not store customer data.',
      },
      {
        id: 'GAI.15',
        question: 'Do you maintain an inventory of AI models, data sources, and components?',
        answer: 'Yes. Our vendor and system inventories list the AI service, the models used, and the data sources that feed it.',
      },
      {
        id: 'GAI.16',
        question: 'How long is customer input retained in the AI system?',
        answer:
          'Build logs are sent to Cloudflare Workers AI only when a customer opts in. They are processed per request and are not retained by the AI service or used for model training. Build logs themselves follow Capgo standard data retention policy.',
      },
    ],
  },
  {
    id: 'qa-governance',
    title: 'Governance, vendors, compliance, and insurance',
    items: [
      {
        id: 'CP.3',
        question: 'Is there a non-retaliation process for internal compliance reporting?',
        answer:
          'Yes. Staff can report concerns through documented reporting channels defined in our policies, and our Code of Business Conduct protects good-faith reporters from retaliation.',
      },
      {
        id: 'OS.7',
        question: 'Do vendor contracts include security provisions?',
        answer:
          'Yes. Our infrastructure providers agreements and DPAs cover access controls, breach notification, sub-processor security, and data ownership. Audit rights are exercised through their independent SOC 2 and ISO 27001 reports.',
      },
      {
        id: 'OS.8',
        question: 'Do you perform vendor security due diligence?',
        answer:
          'Yes. Vendors are identified and risk rated in an annual vendor risk assessment that reviews their security attestations, including access controls, MFA, and encryption, with security commitments and incident notification in their contracts.',
      },
      {
        id: 'SP.4',
        question: 'Is there a defined process for security policy exceptions?',
        answer: 'Yes. Exceptions are documented, risk assessed, approved, and tracked under our Policy Management and Exception Handling policy.',
      },
      {
        id: 'RM.5',
        question: 'Do you maintain cyber insurance?',
        answer: 'No cyber insurance policy today.',
      },
    ],
  },
]
