name: Typo Check

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  CLICOLOR: 1
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Check for Typos
        uses: crate-ci/typos@v1.47.2
